<img src="https://deecamp.chuangxin.com/assets/image/logo_nav_zh.jpg" width="40%">

In [3]:
import pandas as pd
import csv

In [16]:
! ls /data/jupyter_root/ZJ/test1.0

block_1.attributes  block_2.attributes	block_3.attributes
block_1.tuples	    block_2.tuples	block_3.tuples

## 定义一个函数，先输出原始feature文件的P & R，再输出通过D-Cube分块的P & R

名称 | 定义
 --- | ---
TP	| 真实类别为positive，模型预测的类别也为positive
FP	| 预测为positive，但真实类别为negative，真实类别和预测类别不一致
FN	| 预测为negative，但真实类别为positive，真实类别和预测类别不一致
TN	| 真实类别为negative，模型预测的类别也为negative

准确率（accuracy）计算公式如下所示 不计算这个

\begin{equation}\label{equ:accuracy} \mbox{accuracy} = \frac{TP+TN}{TP+TN+FP+FN} = \frac{TP+TN }{\mbox{all data}} \end{equation}

positive class的精确率（precision）计算公式如下

\begin{equation}\label{equ:precision} \mbox{precision} = \frac{TP}{TP+FP} = \frac{TP}{\mbox{预测为positive的样本}} \end{equation}

positive class的召回率（recall）计算公式如下

\begin{equation}\label{equ:recall} \mbox{recall} = \frac{TP}{TP+FN} = \frac{TP}{\mbox{真实为positive的样本}} \end{equation}

In [22]:
def get_PR(f_count,choice,j=3):#f_count：the index of feature;j: index of test; choice: index of block
    
    #准备用于读取数据的 pandas头（防止第一行数据成为标签）
    data_path="/data/jupyter_root/dcube_data/raw_have_name/feature"#feature文件位置
    #try:
    cols = pd.read_csv(data_path+str(f_count)+"/block_1.tuples",nrows=1).columns#先读第一行，用于提取数据维度
    #except e:
    #    print(e)
    #    print("false1")
    #    return 0        

    user_index=['user_name']#初始化一个等待补全的names
    #print(cols.shape[0]-1)
    for i in range(1,cols.shape[0]-1):
            user_index.append(str(i))
    user_index.append('count')#补上最后的count
    
    #开始读取数据
    #result=pd.read_csv(data_path+str(f_count)+"/test"+str(j)+"/block_1.tuples",sep=',',names=user_index)#读取全部的数据，并给上names
    #try:
    if(choice=='all'):#读取blocks.txt
        result=pd.read_csv(data_path+str(f_count)+"/blocks.txt",sep=',',names=user_index)
    elif(choice==1 or choice==2 or choice==3 or choice==4 or choice==5 ):#读取block_choice.tuples
        result=pd.read_csv(data_path+str(f_count)+"/block_"+str(choice)+".tuples",sep=',',names=user_index)
    elif(choice==12 or choice==13 or choice==23 or choice ==123 ):#读取blockchoice.txt
        result=pd.read_csv(data_path+str(f_count)+"/block"+str(choice)+".txt",sep=',',names=user_index)
    #except:
    #    print("false2")
    #    return 0
    names = result['user_name'].drop_duplicates()#预测出坏用户的用户列表
    #print(names)
    dataset = pd.read_csv(open('/data/csv/label_eventsV1.csv','r',encoding = 'gb18030'))#读取总标签数据
    data = dataset[dataset['user_name'].isin(names)][['user_name','label']]#预测出坏用户的真实标签分布
    data = data.drop_duplicates()#去重
    #print(data)

    
    raw_result=pd.read_csv(data_path+str(f_count)+".txt",sep=',',names=user_index)#读取全部的原始数据，并给上names
    raw_names = raw_result['user_name'].drop_duplicates()#原始数据中用户的用户列表
    #print(raw_names)
    raw_data = dataset[dataset['user_name'].isin(raw_names)][['user_name','label']]#原始数据中坏用户的真实标签分布
    raw_data = raw_data.drop_duplicates()#去重
    #print(raw_data)
    
    
    TP=data.label.sum()
    #if(TP==0):
        #return 0
    P=raw_data.label.sum()
    FP=data.label.count()-data.label.sum()
    N=raw_data.label.count()-raw_data.label.sum()
    Precision = (TP/P)/(TP/P+FP/N) #精确率计算

    #data_label_1 = dataset[dataset['label']==1][['user_name','label']] #原数据中label为1的坏用户
    #data_label_1 = data_label_1.drop_duplicates()#去重
    Recall = data.label.sum()/raw_data.label.sum() # 召回率计算
    print(len(names),len(raw_names))
    print("TP",TP,"P",P,"FP",FP,"N",N)
    print('测试特征'+str(f_count)+"_"+str(j)+str(choice))
    print('\t\t精确率 Precision\t= '+str(Precision))
    print('\t\t召回率 Recall   \t= '+str(Recall))
#get_PR(1,1)

In [28]:
def get_no_name_PR(f_count,feature_user,find_user):
    
    dataset = pd.read_csv(open('/data/csv/label_eventsV1.csv','r',encoding = 'gb18030'))#读取总标签数据
    data = dataset[dataset['user_name'].isin(find_user)][['user_name','label']]#预测出坏用户的真实标签分布
    data = data.drop_duplicates()#去重
    #print(data)

    
    #raw_result=pd.read_csv(data_path+str(f_count)+".txt",sep=',',names=user_index)#读取全部的原始数据，并给上names
    #raw_names = raw_result['user_name'].drop_duplicates()#原始数据中用户的用户列表
    #print(raw_names)
    raw_data = dataset[dataset['user_name'].isin(feature_user)][['user_name','label']]#原始数据中坏用户的真实标签分布
    raw_data = raw_data.drop_duplicates()#去重
    #print(raw_data)
    
    
    TP=data.label.sum()
    #if(TP==0):
        #return 0
    P=raw_data.label.sum()
    FP=data.label.count()-data.label.sum()
    N=raw_data.label.count()-raw_data.label.sum()
    Precision = (TP/P)/(TP/P+FP/N) #精确率计算

    #data_label_1 = dataset[dataset['label']==1][['user_name','label']] #原数据中label为1的坏用户
    #data_label_1 = data_label_1.drop_duplicates()#去重
    Recall = data.label.sum()/raw_data.label.sum() # 召回率计算
    print(len(feature_user),len(find_user))
    print("TP",TP,"P",P,"FP",FP,"N",N)
    print('测试特征'+f_count)
    print('\t\t精确率 Precision\t= '+str(Precision))
    print('\t\t召回率 Recall   \t= '+str(Recall))

In [36]:
import re
result_list=pd.read_csv("/data/jupyter_root/dcube_data/raw_no_name/result_list.csv")
#print(result_list)
def get_set(s):
    s=re.sub('[ {}]','',s).split(',')
    def func(x):
        return int(float(x))
    return set(map(func,s))
for i in range(12):
    #try:
        al=get_set(result_list.iloc[i,0])
        get_no_name_PR("feature"+str(i)+'block_1',al,get_set(result_list.iloc[i,1]))
        get_no_name_PR("feature"+str(i)+'block_2',al,get_set(result_list.iloc[i,2]))
        get_no_name_PR("feature"+str(i)+'block_3',al,get_set(result_list.iloc[i,3]))
        get_no_name_PR("feature"+str(i)+'block_4',al,get_set(result_list.iloc[i,4]))
        get_no_name_PR("feature"+str(i)+'block_5',al,get_set(result_list.iloc[i,5]))
    #except:
        #print('false')
        #continue
#for i in range

1135368 33168
TP 219 P 5538 FP 148 N 3871
测试特征feature0block_1
		精确率 Precision	= 0.5084339257022874
		召回率 Recall   	= 0.03954496208017335
1135368 31481
TP 176 P 5538 FP 143 N 3871
测试特征feature0block_2
		精确率 Precision	= 0.4624505338609721
		召回率 Recall   	= 0.03178042614662333
1135368 31320
TP 221 P 5538 FP 148 N 3871
测试特征feature0block_3
		精确率 Precision	= 0.510705832136898
		召回率 Recall   	= 0.03990610328638498
1135368 30959
TP 199 P 5538 FP 139 N 3871
测试特征feature0block_4
		精确率 Precision	= 0.5001775846026683
		召回率 Recall   	= 0.03593355001805706
1135368 29823
TP 192 P 5538 FP 141 N 3871
测试特征feature0block_5
		精确率 Precision	= 0.48765624077318265
		召回率 Recall   	= 0.03466955579631636
1135368 12874
TP 93 P 5538 FP 66 N 3871
测试特征feature1block_1
		精确率 Precision	= 0.4962061223055198
		召回率 Recall   	= 0.016793066088840736
1135368 12401
TP 86 P 5538 FP 52 N 3871
测试特征feature1block_2
		精确率 Precision	= 0.5361823985878154
		召回率 Recall   	= 0.015529071867100036
1135368 12238
TP 65 P 5538 FP 64 N 3871
测试特征feature1block_3
		精确率 Precision	= 0.41517407065788625
		召回率 Recall   	= 0.011737089201877934
1135368 12515
TP 115 P 5538 FP 67 N 3871
测试特征feature1block_4
		精确率 Precision	= 0.5454043133454463
		召回率 Recall   	= 0.02076561935716865
1135368 11120
TP 61 P 5538 FP 53 N 3871
测试特征feature1block_5
		精确率 Precision	= 0.4458288098632103
		召回率 Recall   	= 0.011014806789454677
1135368 28320
TP 248 P 5538 FP 130 N 3871
测试特征feature2block_1
		精确率 Precision	= 0.5714510211030341
		召回率 Recall   	= 0.04478150957024196
1135368 27363
TP 189 P 5538 FP 122 N 3871
测试特征feature2block_2
		精确率 Precision	= 0.5198908513382436
		召回率 Recall   	= 0.03412784398699892
1135368 29088
TP 171 P 5538 FP 123 N 3871
测试特征feature2block_3
		精确率 Precision	= 0.4928401514390056
		召回率 Recall   	= 0.03087757313109426
1135368 27864
TP 183 P 5538 FP 128 N 3871
测试特征feature2block_4
		精确率 Precision	= 0.4998338339482536
		召回率 Recall   	= 0.03304442036836403
1135368 28183
TP 219 P 5538 FP 149 N 3871
测试特征feature2block_5
		精确率 Precision	= 0.5067508074249019
		召回率 Recall   	= 0.03954496208017335
1118213 875
TP 12 P 5484 FP 3 N 3828
测试特征feature3block_1
		精确率 Precision	= 0.7362954414310445
		召回率 Recall   	= 0.002188183807439825
1118213 835
TP 25 P 5484 FP 1 N 3828
测试特征feature3block_2
		精确率 Precision	= 0.9458017077798861
		召回率 Recall   	= 0.004558716265499635
1118213 820
TP 16 P 5484 FP 3 N 3828
测试特征feature3block_3
		精确率 Precision	= 0.7882625482625483
		召回率 Recall   	= 0.0029175784099197666
1118213 805
TP 20 P 5484 FP 3 N 3828
测试特征feature3block_4
		精确率 Precision	= 0.823119597471294
		召回率 Recall   	= 0.0036469730123997084
1118213 802
TP 26 P 5484 FP 4 N 3828
测试特征feature3block_5
		精确率 Precision	= 0.8194032799841929
		召回率 Recall   	= 0.004741064916119621
1118211 115762
TP 1262 P 5484 FP 395 N 3828
测试特征feature4block_1
		精确率 Precision	= 0.6904181665703413
		召回率 Recall   	= 0.2301239970824216
1118211 255522
TP 1853 P 5484 FP 952 N 3828
测试特征feature4block_2
		精确率 Precision	= 0.5760316750327187
		召回率 Recall   	= 0.33789204959883296
1118211 311249
TP 1917 P 5484 FP 1189 N 3828
测试特征feature4block_3
		精确率 Precision	= 0.5295048212133386
		召回率 Recall   	= 0.34956236323851203
1118211 240819
TP 1313 P 5484 FP 984 N 3828
测试特征feature4block_4
		精确率 Precision	= 0.4822453902260704
		召回率 Recall   	= 0.23942377826404085
1118211 155269
TP 663 P 5484 FP 581 N 3828
测试特征feature4block_5
		精确率 Precision	= 0.44337692394772477
		召回率 Recall   	= 0.12089715536105033
1118211 113383
TP 1241 P 5484 FP 378 N 3828
测试特征feature5block_1
		精确率 Precision	= 0.6962040008793141
		召回率 Recall   	= 0.2262946754194019
1118211 256501
TP 1859 P 5484 FP 979 N 3828
测试特征feature5block_2
		精确率 Precision	= 0.5699801234881164
		召回率 Recall   	= 0.3389861415025529
1118211 315760
TP 1936 P 5484 FP 1198 N 3828
测试特征feature5block_3
		精确率 Precision	= 0.5300831709682681
		召回率 Recall   	= 0.3530269876002918
1118211 33034
TP 40 P 5484 FP 152 N 3828
测试特征feature5block_4
		精确率 Precision	= 0.1551858338198093
		召回率 Recall   	= 0.007293946024799417
1118211 739456
TP 3661 P 5484 FP 2695 N 3828
测试特征feature5block_5
		精确率 Precision	= 0.4867145882805982
		召回率 Recall   	= 0.6675784099197666
1118211 28206
TP 378 P 5484 FP 156 N 3828
测试特征feature6block_1
		精确率 Precision	= 0.6284436661559148
		召回率 Recall   	= 0.06892778993435449
1118211 145158
TP 1400 P 5484 FP 505 N 3828
测试特征feature6block_2
		精确率 Precision	= 0.6593001026004414
		召回率 Recall   	= 0.2552881108679796
1118211 280316
TP 1888 P 5484 FP 1034 N 3828
测试特征feature6block_3
		精确率 Precision	= 0.5603520622249514
		召回率 Recall   	= 0.34427425237053244
1118211 287925
TP 1732 P 5484 FP 1129 N 3828
测试特征feature6block_4
		精确率 Precision	= 0.5171063801112068
		召回率 Recall   	= 0.31582786287381476
1118211 208997
TP 1110 P 5484 FP 860 N 3828
测试特征feature6block_5
		精确率 Precision	= 0.47394627297185155
		召回率 Recall   	= 0.2024070021881838
1118211 28411
TP 378 P 5484 FP 157 N 3828
测试特征feature7block_1
		精确率 Precision	= 0.6269504136098705
		召回率 Recall   	= 0.06892778993435449
1118211 143872
TP 1389 P 5484 FP 501 N 3828
测试特征feature7block_2
		精确率 Precision	= 0.6593145132490537
		召回率 Recall   	= 0.25328227571115974
1118211 280851
TP 1878 P 5484 FP 1039 N 3828
测试特征feature7block_3
		精确率 Precision	= 0.5578538138848409
		召回率 Recall   	= 0.3424507658643326
1118211 292231
TP 1751 P 5484 FP 1147 N 3828
测试特征feature7block_4
		精确率 Precision	= 0.5158808882583943
		召回率 Recall   	= 0.31929248723559445
1118211 19049
TP 29 P 5484 FP 80 N 3828
测试特征feature7block_5
		精确率 Precision	= 0.2019383990744581
		召回率 Recall   	= 0.005288110867979577
1118211 98432
TP 1006 P 5484 FP 419 N 3828
测试特征feature8block_1
		精确率 Precision	= 0.6262995294664099
		召回率 Recall   	= 0.18344274252370532
1118211 271734
TP 1809 P 5484 FP 988 N 3828
测试特征feature8block_2
		精确率 Precision	= 0.561032756587435
		召回率 Recall   	= 0.3298687089715536
1118211 585174
TP 3755 P 5484 FP 2114 N 3828
测试特征feature8block_3
		精确率 Precision	= 0.553547390111477
		召回率 Recall   	= 0.6847191830780452
1118211 542180
TP 3408 P 5484 FP 2065 N 3828
测试特征feature8block_4
		精确率 Precision	= 0.5353168637673652
		召回率 Recall   	= 0.6214442013129103
1118211 4291
TP 41 P 5484 FP 33 N 3828
测试特征feature8block_5
		精确率 Precision	= 0.46445312499999997
		召回率 Recall   	= 0.0074762946754194015

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in double_scalars

1118211 4
TP 0 P 5484 FP 0 N 3828
测试特征feature9block_1
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1118211 77556
TP 858 P 5484 FP 361 N 3828
测试特征feature9block_2
		精确率 Precision	= 0.6239231875699544
		召回率 Recall   	= 0.15645514223194748
1118211 228238
TP 1515 P 5484 FP 839 N 3828
测试特征feature9block_3
		精确率 Precision	= 0.5576099447564808
		召回率 Recall   	= 0.2762582056892779
1118211 577342
TP 3698 P 5484 FP 2074 N 3828
测试特征feature9block_4
		精确率 Precision	= 0.5544879387820333
		召回率 Recall   	= 0.674325309992706
1118211 3
TP 0 P 5484 FP 0 N 3828
测试特征feature9block_5
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1118213 99374
TP 707 P 5484 FP 432 N 3828
测试特征feature10block_1
		精确率 Precision	= 0.5332291462252664
		召回率 Recall   	= 0.1289204959883297
1118213 240786
TP 1677 P 5484 FP 1027 N 3828
测试特征feature10block_2
		精确率 Precision	= 0.5326714474331427
		召回率 Recall   	= 0.3057986870897155
1118213 18709
TP 215 P 5484 FP 138 N 3828
测试特征feature10block_3
		精确率 Precision	= 0.5209607219086828
		召回率 Recall   	= 0.039204959883296864
1118213 431139
TP 3061 P 5484 FP 1682 N 3828
测试特征feature10block_4
		精确率 Precision	= 0.5595327118334248
		召回率 Recall   	= 0.5581692195477753
1118213 337472
TP 1655 P 5484 FP 1277 N 3828
测试特征feature10block_5
		精确率 Precision	= 0.4749697265220857
		召回率 Recall   	= 0.30178701677607583
1118213 3
TP 0 P 5484 FP 0 N 3828
测试特征feature11block_1
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1118213 1
TP 0 P 5484 FP 0 N 3828
测试特征feature11block_2
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1118213 1
TP 0 P 5484 FP 0 N 3828
测试特征feature11block_3
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1118213 1
TP 0 P 5484 FP 0 N 3828
测试特征feature11block_4
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1118213 2
TP 0 P 5484 FP 0 N 3828
测试特征feature11block_5
		精确率 Precision	= nan
		召回率 Recall   	= 0.0

In [42]:
import re
result_list=pd.read_csv("/data/jupyter_root/dcube_data/raw_no_name/result_list_feature4.csv")
#print(result_list)
def get_set(s):
    s=re.sub('[ {}]','',s).split(',')
    def func(x):
        return int(float(x))
    return set(map(func,s))
i=0
al=get_set(result_list.iloc[i,0])
for x in range(1,21):
    get_no_name_PR("feature"+str(i)+'block_'+str(x),al,get_set(result_list.iloc[i,x]))

1118213 875
TP 12 P 5484 FP 3 N 3828
测试特征feature0block_1
		精确率 Precision	= 0.7362954414310445
		召回率 Recall   	= 0.002188183807439825
1118213 835
TP 25 P 5484 FP 1 N 3828
测试特征feature0block_2
		精确率 Precision	= 0.9458017077798861
		召回率 Recall   	= 0.004558716265499635
1118213 820
TP 16 P 5484 FP 3 N 3828
测试特征feature0block_3
		精确率 Precision	= 0.7882625482625483
		召回率 Recall   	= 0.0029175784099197666
1118213 805
TP 20 P 5484 FP 3 N 3828
测试特征feature0block_4
		精确率 Precision	= 0.823119597471294
		召回率 Recall   	= 0.0036469730123997084
1118213 802
TP 26 P 5484 FP 4 N 3828
测试特征feature0block_5
		精确率 Precision	= 0.8194032799841929
		召回率 Recall   	= 0.004741064916119621
1118213 791
TP 19 P 5484 FP 2 N 3828
测试特征feature0block_6
		精确率 Precision	= 0.8689605734767025
		召回率 Recall   	= 0.003464624361779723
1118213 772
TP 22 P 5484 FP 4 N 3828
测试特征feature0block_7
		精确率 Precision	= 0.7933529278770065
		召回率 Recall   	= 0.0040116703136396795
1118213 649
TP 20 P 5484 FP 3 N 3828
测试特征feature0block_8
		精确率 Precision	= 0.823119597471294
		召回率 Recall   	= 0.0036469730123997084
1118213 626
TP 8 P 5484 FP 0 N 3828
测试特征feature0block_9
		精确率 Precision	= 1.0
		召回率 Recall   	= 0.0014587892049598833
1118213 577
TP 6 P 5484 FP 4 N 3828
测试特征feature0block_10
		精确率 Precision	= 0.5114911811865313
		召回率 Recall   	= 0.0010940919037199124
1118213 488
TP 1 P 5484 FP 0 N 3828
测试特征feature0block_11
		精确率 Precision	= 1.0
		召回率 Recall   	= 0.00018234865061998541
1118213 465
TP 7 P 5484 FP 1 N 3828
测试特征feature0block_12
		精确率 Precision	= 0.8301115241635688
		召回率 Recall   	= 0.001276440554339898
1118213 455
TP 1 P 5484 FP 2 N 3828
测试特征feature0block_13
		精确率 Precision	= 0.2587185725871857
		召回率 Recall   	= 0.00018234865061998541
1118213 450
TP 2 P 5484 FP 2 N 3828
测试特征feature0block_14
		精确率 Precision	= 0.41108247422680405
		召回率 Recall   	= 0.00036469730123997083
1118213 448
TP 1 P 5484 FP 5 N 3828
测试特征feature0block_15
		精确率 Precision	= 0.12250384024577574
		召回率 Recall   	= 0.00018234865061998541
1118213 444
TP 4 P 5484 FP 2 N 3828
测试特征feature0block_16
		精确率 Precision	= 0.582648401826484
		召回率 Recall   	= 0.0007293946024799417
1118213 434
TP 1 P 5484 FP 2 N 3828
测试特征feature0block_17
		精确率 Precision	= 0.2587185725871857
		召回率 Recall   	= 0.00018234865061998541
1118213 427
TP 4 P 5484 FP 4 N 3828
测试特征feature0block_18
		精确率 Precision	= 0.41108247422680405
		召回率 Recall   	= 0.0007293946024799417
1118213 399
TP 1 P 5484 FP 1 N 3828
测试特征feature0block_19
		精确率 Precision	= 0.41108247422680405
		召回率 Recall   	= 0.00018234865061998541
1118213 396
TP 0 P 5484 FP 0 N 3828
测试特征feature0block_20
		精确率 Precision	= nan
		召回率 Recall   	= 0.0

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in double_scalars

In [39]:
pd.read_csv("/data/jupyter_root/dcube_data/raw_have_name/feature_list.csv")

,Unnamed: 0,Feature_combination,Standard,Poly
0,feature1,"['user_name', 'time_stamp_3hour']",resource_type,nunique
1,feature2,"['user_name', 'time_stamp_3hour']",resource_category,nunique
2,feature3,"['user_name', 'ip_123', 'time_stamp_3hour']",index,count
3,feature4,"['user_name', 'user_agent', 'time_stamp_hour',...",index,count
4,feature5,"['user_name', 'os_version', 'time_stamp_hour',...",index,count
5,feature6,"['user_name', 'os_version', 'time_stamp_hour']",index,count
6,feature7,"['user_name', 'user_agent', 'time_stamp_3hour']",index,count
7,feature8,"['user_name', 'os_version', 'time_stamp_hour']",index,count
8,feature9,"['user_name', 'ip_123', 'time_stamp_6hour', 'e...",index,count
9,feature10,['user_name'],user_agent,nunique
10,feature11,['user_name'],os_version,nunique
11,feature12,['user_name'],ip_1,nunique
12,feature13,['user_name'],ip_12,nunique
13,feature14,['user_name'],ip_123,nunique
14,feature15,['user_name'],ip_1234,nunique
15,feature16,['user_name'],ip_city,nunique
16,feature17,['user_name'],resource_owner,nunique
17,feature18,['user_name'],resource_type,nunique
18,feature19,['user_name'],resource_category,nunique

In [37]:
pd.read_csv("/data/jupyter_root/dcube_data/raw_no_name/feature_list.csv")

   Unnamed: 0             Feature_combination        Standard     Poly
0    feature1            ['time_stamp_3hour']       user_name  nunique
1    feature2             ['time_stamp_hour']      user_agent  nunique
2    feature3            ['time_stamp_3hour']  resource_owner  nunique
3    feature4                     ['ip_1234']       user_name  nunique
4    feature5        ['ip_123', 'user_agent']       user_name  nunique
5    feature6        ['ip_123', 'os_version']       user_name  nunique
6    feature7        ['ip_123', 'user_agent']       user_name    count
7    feature8        ['ip_123', 'os_version']       user_name    count
8    feature9  ['ip_123', 'time_stamp_3hour']       user_name  nunique
9   feature10  ['ip_123', 'time_stamp_3hour']       user_name    count
10  feature11  ['ip_1234', 'time_stamp_hour']       user_name  nunique
11  feature12  ['ip_1234', 'time_stamp_hour']       user_name    count

In [23]:
for i in range(1,10):
    #for j in range(51,136):
        #j=3
        #try:
            #if(j==3):
                get_PR(i,1)
                get_PR(i,2)
                get_PR(i,3)
                get_PR(i,4)
                get_PR(i,5)
                #get_PR(i,j,'all')
                #get_PR(i,j,12)
                #get_PR(i,j,13)
                #get_PR(i,j,23)
                #get_PR(i,j,123)
     # except:
     #     print("false")
     #     continue

72263 1135368
TP 1104 P 5538 FP 634 N 3871
测试特征1_31
		精确率 Precision	= 0.5489739071992207
		召回率 Recall   	= 0.19934994582881907
16136 1135368
TP 276 P 5538 FP 164 N 3871
测试特征1_32
		精确率 Precision	= 0.5405144518847249
		召回率 Recall   	= 0.04983748645720477
358378 1135368
TP 3321 P 5538 FP 1764 N 3871
测试特征1_33
		精确率 Precision	= 0.5682123852406292
		召回率 Recall   	= 0.5996749729144095
5486 1135368
TP 82 P 5538 FP 61 N 3871
测试特征1_34
		精确率 Precision	= 0.48443623710396194
		召回率 Recall   	= 0.014806789454676778
128751 1135368
TP 1378 P 5538 FP 849 N 3871
测试特征1_35
		精确率 Precision	= 0.5315103626943005
		召回率 Recall   	= 0.24882629107981222
71176 1135368
TP 1096 P 5538 FP 616 N 3871
测试特征2_31
		精确率 Precision	= 0.5542987584047293
		召回率 Recall   	= 0.19790538100397256

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:52: RuntimeWarning: invalid value encountered in double_scalars

5 1135368
TP 0 P 5538 FP 0 N 3871
测试特征2_32
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
14611 1135368
TP 259 P 5538 FP 155 N 3871
测试特征2_33
		精确率 Precision	= 0.5387427800098765
		召回率 Recall   	= 0.04676778620440592
361925 1135368
TP 3373 P 5538 FP 1799 N 3871
测试特征2_34
		精确率 Precision	= 0.5672036332287781
		召回率 Recall   	= 0.6090646442759119
4226 1135368
TP 68 P 5538 FP 55 N 3871
测试特征2_35
		精确率 Precision	= 0.4635781183407359
		召回率 Recall   	= 0.012278801011195377
2 1118211
TP 0 P 5484 FP 0 N 3828
测试特征3_31
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1 1118211
TP 0 P 5484 FP 0 N 3828
测试特征3_32
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1 1118211
TP 0 P 5484 FP 0 N 3828
测试特征3_33
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1 1118211
TP 0 P 5484 FP 0 N 3828
测试特征3_34
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
2 1118211
TP 0 P 5484 FP 0 N 3828
测试特征3_35
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
349513 1135368
TP 3923 P 5538 FP 2038 N 3871
测试特征4_31
		精确率 Precision	= 0.5736520373671016
		召回率 Recall   	= 0.7083784759841097
713426 1135368
TP 1827 P 5538 FP 2087 N 3871
测试特征4_32
		精确率 Precision	= 0.3796173004332822
		召回率 Recall   	= 0.32990249187432286
1 1135368
TP 0 P 5538 FP 0 N 3871
测试特征4_33
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
168488 1135368
TP 196 P 5538 FP 770 N 3871
测试特征4_34
		精确率 Precision	= 0.15104909917945059
		召回率 Recall   	= 0.03539183820873962
1 1135368
TP 0 P 5538 FP 0 N 3871
测试特征4_35
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
350610 1135368
TP 3923 P 5538 FP 2043 N 3871
测试特征5_31
		精确率 Precision	= 0.573052626621661
		召回率 Recall   	= 0.7083784759841097
820096 1135368
TP 1872 P 5538 FP 2330 N 3871
测试特征5_32
		精确率 Precision	= 0.3596274590259122
		召回率 Recall   	= 0.3380281690140845
222322 1135368
TP 1209 P 5538 FP 971 N 3871
测试特征5_33
		精确率 Precision	= 0.4653311773168452
		召回率 Recall   	= 0.21830985915492956
57193 1135368
TP 189 P 5538 FP 232 N 3871
测试特征5_34
		精确率 Precision	= 0.36282796122860395
		召回率 Recall   	= 0.03412784398699892
1 1135368
TP 0 P 5538 FP 0 N 3871
测试特征5_35
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1 1135368
TP 0 P 5538 FP 0 N 3871
测试特征6_31
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
350825 1135368
TP 3925 P 5538 FP 2043 N 3871
测试特征6_32
		精确率 Precision	= 0.5731773229541529
		召回率 Recall   	= 0.7087396171903214
466139 1135368
TP 1123 P 5538 FP 1155 N 3871
测试特征6_33
		精确率 Precision	= 0.40462825834691285
		召回率 Recall   	= 0.20278078728782953
2 1135368
TP 0 P 5538 FP 0 N 3871
测试特征6_34
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
456523 1135368
TP 858 P 5538 FP 1466 N 3871
测试特征6_35
		精确率 Precision	= 0.29032434017195413
		召回率 Recall   	= 0.15492957746478872
1 1135368
TP 0 P 5538 FP 0 N 3871
测试特征7_31
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
351346 1135368
TP 3912 P 5538 FP 2045 N 3871
测试特征7_32
		精确率 Precision	= 0.5721259810034258
		召回率 Recall   	= 0.7063921993499458
1 1135368
TP 0 P 5538 FP 0 N 3871
测试特征7_33
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
742821 1135368
TP 2297 P 5538 FP 2186 N 3871
测试特征7_34
		精确率 Precision	= 0.42345893644344357
		召回率 Recall   	= 0.4147706753340556
1 1135368
TP 0 P 5538 FP 0 N 3871
测试特征7_35
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1 1135368
TP 0 P 5538 FP 0 N 3871
测试特征8_31
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
350825 1135368
TP 3925 P 5538 FP 2043 N 3871
测试特征8_32
		精确率 Precision	= 0.5731773229541529
		召回率 Recall   	= 0.7087396171903214
466139 1135368
TP 1123 P 5538 FP 1155 N 3871
测试特征8_33
		精确率 Precision	= 0.40462825834691285
		召回率 Recall   	= 0.20278078728782953
2 1135368
TP 0 P 5538 FP 0 N 3871
测试特征8_34
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
456523 1135368
TP 858 P 5538 FP 1466 N 3871
测试特征8_35
		精确率 Precision	= 0.29032434017195413
		召回率 Recall   	= 0.15492957746478872
2 1118211
TP 0 P 5484 FP 0 N 3828
测试特征9_31
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
3 1118211
TP 0 P 5484 FP 0 N 3828
测试特征9_32
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
1 1118211
TP 0 P 5484 FP 0 N 3828
测试特征9_33
		精确率 Precision	= nan
		召回率 Recall   	= 0.0
850725 1118211
TP 4776 P 5484 FP 3018 N 3828
测试特征9_34
		精确率 Precision	= 0.5248586694777747
		召回率 Recall   	= 0.8708971553610503
343339 1118211
TP 1323 P 5484 FP 1330 N 3828
测试特征9_35
		精确率 Precision	= 0.4098055342201317
		召回率 Recall   	= 0.2412472647702407

In [25]:
def get_PR_mini(f_count,choice,j=3):#f_count：the index of feature;j: index of test; choice: index of block
    
    #准备用于读取数据的 pandas头（防止第一行数据成为标签）
    data_path="/data/jupyter_root/dcube_data/mini_have_name/feature"#feature文件位置
    #try:
    cols = pd.read_csv(data_path+str(f_count)+"/block_1.tuples",nrows=1).columns#先读第一行，用于提取数据维度
    #except e:
    #    print(e)
    #    print("false1")
    #    return 0        

    user_index=['user_name']#初始化一个等待补全的names
    #print(cols.shape[0]-1)
    for i in range(1,cols.shape[0]-1):
            user_index.append(str(i))
    user_index.append('count')#补上最后的count
    
    #开始读取数据
    #result=pd.read_csv(data_path+str(f_count)+"/test"+str(j)+"/block_1.tuples",sep=',',names=user_index)#读取全部的数据，并给上names
    #try:
    if(choice=='all'):#读取blocks.txt
        result=pd.read_csv(data_path+str(f_count)+"/blocks.txt",sep=',',names=user_index)
    elif(choice==1 or choice==2 or choice==3 or choice==4 or choice==5 ):#读取block_choice.tuples
        result=pd.read_csv(data_path+str(f_count)+"/block_"+str(choice)+".tuples",sep=',',names=user_index)
    elif(choice==12 or choice==13 or choice==23 or choice ==123 ):#读取blockchoice.txt
        result=pd.read_csv(data_path+str(f_count)+"/block"+str(choice)+".txt",sep=',',names=user_index)
    #except:
    #    print("false2")
    #    return 0
    names = result['user_name'].drop_duplicates()#预测出坏用户的用户列表
    #print(names)
    dataset = pd.read_csv(open('/data/csv/label_eventsV1.csv','r',encoding = 'gb18030'))#读取总标签数据
    data = dataset[dataset['user_name'].isin(names)][['user_name','label']]#预测出坏用户的真实标签分布
    data = data.drop_duplicates()#去重
    #print(data)

    
    raw_result=pd.read_csv(data_path+str(f_count)+".txt",sep=',',names=user_index)#读取全部的原始数据，并给上names
    raw_names = raw_result['user_name'].drop_duplicates()#原始数据中用户的用户列表
    #print(raw_names)
    raw_data = dataset[dataset['user_name'].isin(raw_names)][['user_name','label']]#原始数据中坏用户的真实标签分布
    raw_data = raw_data.drop_duplicates()#去重
    #print(raw_data)
    
    
    TP=data.label.sum()
    #if(TP==0):
        #return 0
    P=raw_data.label.sum()
    FP=data.label.count()-data.label.sum()
    N=raw_data.label.count()-raw_data.label.sum()
    Precision = (TP/P)/(TP/P+FP/N) #精确率计算

    #data_label_1 = dataset[dataset['label']==1][['user_name','label']] #原数据中label为1的坏用户
    #data_label_1 = data_label_1.drop_duplicates()#去重
    Recall = data.label.sum()/raw_data.label.sum() # 召回率计算
    print(len(names),len(raw_names))
    print("TP",TP,"P",P,"FP",FP,"N",N)
    print('测试特征'+str(f_count)+"_"+str(j)+str(choice))
    print('\t\t精确率 Precision\t= '+str(Precision))
    print('\t\t召回率 Recall   \t= '+str(Recall))

In [26]:
for i in range(1,10):
    #for j in range(51,136):
        #j=3
        #try:
            #if(j==3):
                get_PR_mini(i,1)
                get_PR_mini(i,2)
                get_PR_mini(i,3)
                get_PR_mini(i,4)
                get_PR_mini(i,5)

1344 9409
TP 848 P 5538 FP 496 N 3871
测试特征1_31
		精确率 Precision	= 0.5444285520949155
		召回率 Recall   	= 0.1531238714337306
1949 9409
TP 1282 P 5538 FP 667 N 3871
测试特征1_32
		精确率 Precision	= 0.5732848547467628
		召回率 Recall   	= 0.23149151318165404
3 9409
TP 2 P 5538 FP 1 N 3871
测试特征1_33
		精确率 Precision	= 0.5829819277108435
		召回率 Recall   	= 0.00036114120621162876
4450 9409
TP 2880 P 5538 FP 1570 N 3871
测试特征1_34
		精确率 Precision	= 0.5618304361104139
		召回率 Recall   	= 0.5200433369447454
3 9409
TP 2 P 5538 FP 1 N 3871
测试特征1_35
		精确率 Precision	= 0.5829819277108435
		召回率 Recall   	= 0.00036114120621162876
1772 9409
TP 1152 P 5538 FP 620 N 3871
测试特征2_31
		精确率 Precision	= 0.5649840515943845
		召回率 Recall   	= 0.20801733477789816
1 9409
TP 0 P 5538 FP 1 N 3871
测试特征2_32
		精确率 Precision	= 0.0
		召回率 Recall   	= 0.0
1 9409
TP 0 P 5538 FP 1 N 3871
测试特征2_33
		精确率 Precision	= 0.0
		召回率 Recall   	= 0.0
383 9409
TP 232 P 5538 FP 151 N 3871
测试特征2_34
		精确率 Precision	= 0.5178266861172456
		召回率 Recall   	= 0.041892379920548936
5125 9409
TP 3334 P 5538 FP 1791 N 3871
测试特征2_35
		精确率 Precision	= 0.5654419519540255
		召回率 Recall   	= 0.6020223907547851
1 9312
TP 0 P 5484 FP 1 N 3828
测试特征3_31
		精确率 Precision	= 0.0
		召回率 Recall   	= 0.0
33 9312
TP 1 P 5484 FP 32 N 3828
测试特征3_32
		精确率 Precision	= 0.021347788262062503
		召回率 Recall   	= 0.00018234865061998541
1607 9312
TP 1104 P 5484 FP 503 N 3828
测试特征3_33
		精确率 Precision	= 0.6050645394615899
		召回率 Recall   	= 0.2013129102844639
3646 9312
TP 2109 P 5484 FP 1537 N 3828
测试特征3_34
		精确率 Precision	= 0.4892239561366512
		召回率 Recall   	= 0.38457330415754926
27 9312
TP 0 P 5484 FP 27 N 3828
测试特征3_35
		精确率 Precision	= 0.0
		召回率 Recall   	= 0.0
5956 9409
TP 3924 P 5538 FP 2032 N 3871
测试特征4_31
		精确率 Precision	= 0.5744352952121202
		召回率 Recall   	= 0.7085590465872156
3633 9409
TP 1783 P 5538 FP 1850 N 3871
测试特征4_32
		精确率 Precision	= 0.40251210497190437
		召回率 Recall   	= 0.32195738533766705
298 9409
TP 42 P 5538 FP 256 N 3871
测试特征4_33
		精确率 Precision	= 0.10287981471989674
		召回率 Recall   	= 0.007583965330444204
711 9409
TP 133 P 5538 FP 578 N 3871
测试特征4_34
		精确率 Precision	= 0.13855482806292144
		召回率 Recall   	= 0.02401589021307331
541 9409
TP 121 P 5538 FP 420 N 3871
测试特征4_35
		精确率 Precision	= 0.16762067471122988
		召回率 Recall   	= 0.021849042975803538
5966 9409
TP 3926 P 5538 FP 2040 N 3871
测试特征5_31
		精确率 Precision	= 0.5735990995455532
		召回率 Recall   	= 0.7089201877934272
4320 9409
TP 1932 P 5538 FP 2388 N 3871
测试特征5_32
		精确率 Precision	= 0.3612319762498312
		召回率 Recall   	= 0.3488624052004334
183 9409
TP 51 P 5538 FP 132 N 3871
测试特征5_33
		精确率 Precision	= 0.2126380142109804
		召回率 Recall   	= 0.009209100758396533
54 9409
TP 29 P 5538 FP 25 N 3871
测试特征5_34
		精确率 Precision	= 0.44776613524045805
		召回率 Recall   	= 0.005236547490068617
35 9409
TP 10 P 5538 FP 25 N 3871
测试特征5_35
		精确率 Precision	= 0.2185030480921201
		召回率 Recall   	= 0.0018057060310581437
4929 9409
TP 3256 P 5538 FP 1673 N 3871
测试特征6_31
		精确率 Precision	= 0.5763385240785494
		召回率 Recall   	= 0.5879378837125316
4598 9409
TP 2419 P 5538 FP 2179 N 3871
测试特征6_32
		精确率 Precision	= 0.43692965007035756
		召回率 Recall   	= 0.43680028891296496
418 9409
TP 76 P 5538 FP 342 N 3871
测试特征6_33
		精确率 Precision	= 0.13444706863017505
		召回率 Recall   	= 0.013723365836041893
644 9409
TP 116 P 5538 FP 528 N 3871
测试特征6_34
		精确率 Precision	= 0.13312264682339686
		召回率 Recall   	= 0.020946189960274468
2 9409
TP 0 P 5538 FP 2 N 3871
测试特征6_35
		精确率 Precision	= 0.0
		召回率 Recall   	= 0.0
2845 9409
TP 1861 P 5538 FP 984 N 3871
测试特征7_31
		精确率 Precision	= 0.5693311551439887
		召回率 Recall   	= 0.33604189237992055
5642 9409
TP 3527 P 5538 FP 2115 N 3871
测试特征7_32
		精确率 Precision	= 0.5382432319437519
		召回率 Recall   	= 0.6368725171542073
1505 9409
TP 485 P 5538 FP 1020 N 3871
测试特征7_33
		精确率 Precision	= 0.2494534090599566
		召回率 Recall   	= 0.08757674250631997
321 9409
TP 54 P 5538 FP 267 N 3871
测试特征7_34
		精确率 Precision	= 0.12385878839590445
		召回率 Recall   	= 0.009750812567713976
426 9409
TP 178 P 5538 FP 248 N 3871
测试特征7_35
		精确率 Precision	= 0.3340851855694796
		召回率 Recall   	= 0.03214156735283496
4929 9409
TP 3256 P 5538 FP 1673 N 3871
测试特征8_31
		精确率 Precision	= 0.5763385240785494
		召回率 Recall   	= 0.5879378837125316
4598 9409
TP 2419 P 5538 FP 2179 N 3871
测试特征8_32
		精确率 Precision	= 0.43692965007035756
		召回率 Recall   	= 0.43680028891296496
418 9409
TP 76 P 5538 FP 342 N 3871
测试特征8_33
		精确率 Precision	= 0.13444706863017505
		召回率 Recall   	= 0.013723365836041893
644 9409
TP 116 P 5538 FP 528 N 3871
测试特征8_34
		精确率 Precision	= 0.13312264682339686
		召回率 Recall   	= 0.020946189960274468
2 9409
TP 0 P 5538 FP 2 N 3871
测试特征8_35
		精确率 Precision	= 0.0
		召回率 Recall   	= 0.0
4420 9312
TP 2896 P 5484 FP 1524 N 3828
测试特征9_31
		精确率 Precision	= 0.5701589590024514
		召回率 Recall   	= 0.5280816921954777
6911 9312
TP 3819 P 5484 FP 3092 N 3828
测试特征9_32
		精确率 Precision	= 0.4629873769859443
		召回率 Recall   	= 0.6963894967177243
550 9312
TP 298 P 5484 FP 252 N 3828
测试特征9_33
		精确率 Precision	= 0.45218954839077946
		召回率 Recall   	= 0.054339897884755656
9312 9312
TP 5484 P 5484 FP 3828 N 3828
测试特征9_34
		精确率 Precision	= 0.5
		召回率 Recall   	= 1.0
9312 9312
TP 5484 P 5484 FP 3828 N 3828
测试特征9_35
		精确率 Precision	= 0.5
		召回率 Recall   	= 1.0

In [51]:
#特征取交集测试
get_PR(57,3,1)
get_PR(57,3,2)
import pandas as pd
dataset = pd.read_csv(open('/data/csv/label_eventsV1.csv','r',encoding = 'gb18030'))#读取总标签数据
user_index=['user_name']#初始化一个等待补全的names
#print(cols.shape[0]-1)
for i in range(1,3):
        user_index.append(str(i))
user_index.append('count')
user_index.append('now')
result_1=pd.read_csv("/data/jupyter_root/dcube_data/feature57/block_1.tuples",sep=',',names=user_index)

#user_index.pop()
result_2=pd.read_csv("/data/jupyter_root/dcube_data/feature57/block_2.tuples",sep=',',names=user_index)
names=set(result_1['user_name'].drop_duplicates().values)&set(result_2['user_name'].drop_duplicates().values)
data = dataset[dataset['user_name'].isin(names)][['user_name','label']]#预测出坏用户的真实标签分布
data = data.drop_duplicates()

#user_index.append('now')
raw_result=pd.read_csv("/data/jupyter_root/dcube_data/feature57.txt",sep=',',names=user_index)#读取全部的原始数据，并给上names
raw_names = raw_result['user_name'].drop_duplicates()#原始数据中用户的用户列表
#print(raw_names)
raw_data = dataset[dataset['user_name'].isin(raw_names)][['user_name','label']]#原始数据中用户的真实标签分布
raw_data = raw_data.drop_duplicates()#去重

TP=data.label.sum()
P=raw_data.label.sum()
FP=data.label.count()-data.label.sum()
N=raw_data.label.count()-raw_data.label.sum()
Precision = (TP/P)/(TP/P+FP/N) #精确率计算


    #data_label_1 = dataset[dataset['label']==1][['user_name','label']] #原数据中label为1的坏用户
    #data_label_1 = data_label_1.drop_duplicates()#去重
Recall = data.label.sum()/raw_data.label.sum() # 召回率计算
print("TP",TP,"P",P,"FP",FP,"N",N)
print('\t\t精确率 Precision\t= '+str(Precision))
print('\t\t召回率 Recall   \t= '+str(Recall))
#user_index.pop()

raw_result=pd.read_csv("/data/jupyter_root/dcube_data/feature57.txt",sep=',',names=user_index)#读取全部的原始数据，并给上names
raw_names = raw_result['user_name'].drop_duplicates()#原始数据中用户的用户列表
#print(raw_names)
raw_data = dataset[dataset['user_name'].isin(raw_names)][['user_name','label']]#原始数据中坏用户的真实标签分布
raw_data = raw_data.drop_duplicates()#去重

TP=data.label.sum()
P=raw_data.label.sum()
FP=data.label.count()-data.label.sum()
N=raw_data.label.count()-raw_data.label.sum()
Precision = (TP/P)/(TP/P+FP/N) #精确率计算

    #data_label_1 = dataset[dataset['label']==1][['user_name','label']] #原数据中label为1的坏用户
    #data_label_1 = data_label_1.drop_duplicates()#去重
Recall = data.label.sum()/raw_data.label.sum() # 召回率计算
print("TP",TP,"P",P,"FP",FP,"N",N)
print('\t\t精确率 Precision\t= '+str(Precision))
print('\t\t召回率 Recall   \t= '+str(Recall))

TP 3244 P 5538 FP 1666 N 3871
测试特征57_31
		精确率 Precision	= 0.5764607439131921
		召回率 Recall   	= 0.5857710364752619
TP 2431 P 5538 FP 2186 N 3871
测试特征57_32
		精确率 Precision	= 0.437358053498462
		召回率 Recall   	= 0.43896713615023475
TP 172 P 5538 FP 160 N 3871
		精确率 Precision	= 0.4290324326692837
		召回率 Recall   	= 0.031058143734200072
TP 172 P 5538 FP 160 N 3871
		精确率 Precision	= 0.4290324326692837
		召回率 Recall   	= 0.031058143734200072

# 精确率Precision的计算

# 召回率Recall的计算

In [5]:
pd.set_option('max_row',200) 
pd.set_option('display.max_colwidth', 100)
pd.read_csv("/data/jupyter_root/dcube_data/have_name/feature_list.csv",sep=',')

,Unnamed: 0,Feature_combination,Standard,Poly,user_name_dic,user_name_num
0,feature1,['user_name'],user_agent,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
1,feature2,"['user_name', 'time_stamp_day']",user_agent,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
2,feature3,"['user_name', 'time_stamp_hour']",user_agent,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
3,feature4,"['user_name', 'time_stamp_3hour']",user_agent,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
4,feature5,"['user_name', 'time_stamp_6hour']",user_agent,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
5,feature6,['user_name'],os_version,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
6,feature7,"['user_name', 'time_stamp_day']",os_version,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
7,feature8,"['user_name', 'time_stamp_hour']",os_version,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
8,feature9,"['user_name', 'time_stamp_3hour']",os_version,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
9,feature10,"['user_name', 'time_stamp_6hour']",os_version,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
10,feature11,['user_name'],ip_1,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
11,feature12,"['user_name', 'time_stamp_day']",ip_1,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
12,feature13,"['user_name', 'time_stamp_hour']",ip_1,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
13,feature14,"['user_name', 'time_stamp_3hour']",ip_1,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
14,feature15,"['user_name', 'time_stamp_6hour']",ip_1,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
15,feature16,['user_name'],ip_12,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
16,feature17,"['user_name', 'time_stamp_day']",ip_12,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
17,feature18,"['user_name', 'time_stamp_hour']",ip_12,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
18,feature19,"['user_name', 'time_stamp_3hour']",ip_12,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
19,feature20,"['user_name', 'time_stamp_6hour']",ip_12,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
20,feature21,['user_name'],ip_123,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
21,feature22,"['user_name', 'time_stamp_day']",ip_123,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
22,feature23,"['user_name', 'time_stamp_hour']",ip_123,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
23,feature24,"['user_name', 'time_stamp_3hour']",ip_123,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
24,feature25,"['user_name', 'time_stamp_6hour']",ip_123,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
25,feature26,['user_name'],ip_1234,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
26,feature27,"['user_name', 'time_stamp_day']",ip_1234,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
27,feature28,"['user_name', 'time_stamp_hour']",ip_1234,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
28,feature29,"['user_name', 'time_stamp_3hour']",ip_1234,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
29,feature30,"['user_name', 'time_stamp_6hour']",ip_1234,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
30,feature31,['user_name'],ip_city,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
31,feature32,"['user_name', 'time_stamp_day']",ip_city,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
32,feature33,"['user_name', 'time_stamp_hour']",ip_city,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
33,feature34,"['user_name', 'time_stamp_3hour']",ip_city,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
34,feature35,"['user_name', 'time_stamp_6hour']",ip_city,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
35,feature36,['user_name'],resource_owner,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
36,feature37,"['user_name', 'time_stamp_day']",resource_owner,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
37,feature38,"['user_name', 'time_stamp_hour']",resource_owner,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
38,feature39,"['user_name', 'time_stamp_3hour']",resource_owner,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
39,feature40,"['user_name', 'time_stamp_6hour']",resource_owner,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
40,feature41,['user_name'],resource_type,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
41,feature42,"['user_name', 'time_stamp_day']",resource_type,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
42,feature43,"['user_name', 'time_stamp_hour']",resource_type,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
43,feature44,"['user_name', 'time_stamp_3hour']",resource_type,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
44,feature45,"['user_name', 'time_stamp_6hour']",resource_type,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
45,feature46,['user_name'],resource_category,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
46,feature47,"['user_name', 'time_stamp_day']",resource_category,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
47,feature48,"['user_name', 'time_stamp_hour']",resource_category,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
48,feature49,"['user_name', 'time_stamp_3hour']",resource_category,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
49,feature50,"['user_name', 'time_stamp_6hour']",resource_category,nunique,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
50,feature51,"['user_name', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
51,feature52,"['user_name', 'time_stamp_day']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
52,feature53,"['user_name', 'time_stamp_hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
53,feature54,"['user_name', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
54,feature55,"['user_name', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
55,feature56,"['user_name', 'user_agent', 'time_stamp_day']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
56,feature57,"['user_name', 'user_agent', 'time_stamp_hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
57,feature58,"['user_name', 'user_agent', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
58,feature59,"['user_name', 'user_agent', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
59,feature60,"['user_name', 'os_version', 'time_stamp_day']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
60,feature61,"['user_name', 'os_version', 'time_stamp_hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
61,feature62,"['user_name', 'os_version', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
62,feature63,"['user_name', 'os_version', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
63,feature64,"['user_name', 'ip_1', 'time_stamp_day']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
64,feature65,"['user_name', 'ip_1', 'time_stamp_hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
65,feature66,"['user_name', 'ip_1', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
66,feature67,"['user_name', 'ip_1', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
67,feature68,"['user_name', 'ip_12', 'time_stamp_day']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
68,feature69,"['user_name', 'ip_12', 'time_stamp_hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
69,feature70,"['user_name', 'ip_12', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
70,feature71,"['user_name', 'ip_12', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
71,feature72,"['user_name', 'ip_123', 'time_stamp_day']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
72,feature73,"['user_name', 'ip_123', 'time_stamp_hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
73,feature74,"['user_name', 'ip_123', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
74,feature75,"['user_name', 'ip_123', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
75,feature76,"['user_name', 'ip_1234', 'time_stamp_day']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
76,feature77,"['user_name', 'ip_1234', 'time_stamp_hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
77,feature78,"['user_name', 'ip_1234', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
78,feature79,"['user_name', 'ip_1234', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
79,feature80,"['user_name', 'ip_city', 'time_stamp_day']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9107
80,feature81,"['user_name', 'ip_city', 'time_stamp_hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9107
81,feature82,"['user_name', 'ip_city', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9107
82,feature83,"['user_name', 'ip_city', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9107
83,feature84,"['user_name', 'resource_owner', 'time_stamp_day']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
84,feature85,"['user_name', 'resource_owner', 'time_stamp_hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
85,feature86,"['user_name', 'resource_owner', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
86,feature87,"['user_name', 'resource_owner', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
87,feature88,"['user_name', 'resource_type', 'time_stamp_day']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
88,feature89,"['user_name', 'resource_type', 'time_stamp_hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
89,feature90,"['user_name', 'resource_type', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
90,feature91,"['user_name', 'resource_type', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
91,feature92,"['user_name', 'resource_category', 'time_stamp_day']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
92,feature93,"['user_name', 'resource_category', 'time_stamp_hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
93,feature94,"['user_name', 'resource_category', 'time_stamp_3hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
94,feature95,"['user_name', 'resource_category', 'time_stamp_6hour']",index,count,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...",7408
95,feature96,"['user_name', 'user_agent', 'time_stamp_day', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
96,feature97,"['user_name', 'user_agent', 'time_stamp_hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
97,feature98,"['user_name', 'user_agent', 'time_stamp_3hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
98,feature99,"['user_name', 'user_agent', 'time_stamp_6hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
99,feature100,"['user_name', 'os_version', 'time_stamp_day', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
100,feature101,"['user_name', 'os_version', 'time_stamp_hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
101,feature102,"['user_name', 'os_version', 'time_stamp_3hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
102,feature103,"['user_name', 'os_version', 'time_stamp_6hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9409
103,feature104,"['user_name', 'ip_1', 'time_stamp_day', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
104,feature105,"['user_name', 'ip_1', 'time_stamp_hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
105,feature106,"['user_name', 'ip_1', 'time_stamp_3hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
106,feature107,"['user_name', 'ip_1', 'time_stamp_6hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
107,feature108,"['user_name', 'ip_12', 'time_stamp_day', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
108,feature109,"['user_name', 'ip_12', 'time_stamp_hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
109,feature110,"['user_name', 'ip_12', 'time_stamp_3hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
110,feature111,"['user_name', 'ip_12', 'time_stamp_6hour', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312
111,feature112,"['user_name', 'ip_123', 'time_stamp_day', 'event_type']",index,count,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...",9312

In [61]:
pwd

'/data/jupyter_root/LSK'

In [21]:
import pandas as pd
user_index=['user_name']#初始化一个等待补全的names
#print(cols.shape[0]-1)
for i in range(1,3):
        user_index.append(str(i))
user_index.append('count')
result_1=pd.read_csv("./block12.txt",sep=',',names=user_index)
result_2=pd.read_csv("./block13.txt",sep=',',names=user_index)
set(result_1['user_name'].drop_duplicates().values)&set(result_2['user_name'].drop_duplicates().values)
fet

{1343494,
 458762,
 1310734,
 1343510,
 1540121,
 1671197,
 65569,
 32805,
 65598,
 524351,
 393281,
 524359,
 1540168,
 1638472,
 524364,
 65614,
 1540176,
 393300,
 65629,
 1146980,
 262247,
 196712,
 65645,
 360561,
 262258,
 1540214,
 1605754,
 229504,
 1409157,
 393356,
 1540237,
 1310879,
 1376418,
 1376419,
 1540260,
 262312,
 1671346,
 1179832,
 65722,
 1179837,
 65728,
 393420,
 491735,
 1147095,
 1540313,
 1147101,
 295139,
 1343718,
 1179879,
 327915,
 65779,
 327928,
 262394,
 524541,
 295167,
 1540356,
 1343750,
 1540359,
 1409286,
 1179919,
 1540369,
 65821,
 1507622,
 1540391,
 1311025,
 1179954,
 1147187,
 459060,
 1212727,
 1179962,
 393538,
 1507655,
 1147208,
 1179977,
 1507657,
 1507668,
 1507673,
 1540452,
 1507685,
 1540453,
 1671524,
 1507689,
 1507693,
 98670,
 1507698,
 1343865,
 196993,
 1507716,
 1507719,
 98696,
 524681,
 1507724,
 1573265,
 1507730,
 655763,
 197018,
 131491,
 1540516,
 393640,
 524723,
 1507763,
 1507769,
 131514,
 491981,
 1507792,
 1507794,
 1311190,
 1081816,
 1311211,
 1540588,
 393717,
 1671675,
 1311229,
 1180162,
 524803,
 393743,
 1540628,
 1180187,
 1540635,
 1081888,
 328230,
 1311275,
 1507883,
 1540656,
 1344050,
 1671735,
 197182,
 197196,
 66125,
 492110,
 1638988,
 688727,
 459362,
 393834,
 524909,
 1245819,
 1376903,
 66190,
 66192,
 524951,
 98976,
 656035,
 1540773,
 1180357,
 1606341,
 66251,
 1442513,
 99027,
 1671898,
 164570,
 33502,
 1508067,
 1180391,
 492289,
 197383,
 1671944,
 1180425,
 1082127,
 262928,
 1180441,
 1180442,
 1573659,
 1180450,
 492327,
 394024,
 66345,
 1180463,
 1311552,
 492354,
 1180485,
 1180492,
 1639246,
 1180498,
 1377121,
 492386,
 1180521,
 1180528,
 1180529,
 1180536,
 99206,
 394125,
 1180565,
 1180566,
 1180568,
 1311644,
 1180587,
 328624,
 1180594,
 1639371,
 66517,
 1180634,
 1508319,
 1311715,
 1180651,
 1180652,
 1180659,
 1180660,
 1508344,
 33789,
 1508352,
 1508359,
 1180681,
 1508361,
 1573897,
 1508387,
 1508392,
 1541160,
 66605,
 1508399,
 459824,
 66619,
 1180731,
 1508412,
 1180735,
 1508416,
 328769,
 1344587,
 1180750,
 197712,
 1180752,
 459866,
 197727,
 1311840,
 361573,
 1082490,
 1311869,
 99463,
 1344655,
 197776,
 1672340,
 197800,
 197806,
 197807,
 230578,
 66739,
 1344694,
 66743,
 394423,
 1180857,
 394430,
 99519,
 394436,
 197829,
 1475780,
 460005,
 1344741,
 263399,
 460010,
 197869,
 34039,
 460027,
 197884,
 197887,
 197888,
 230661,
 230664,
 34057,
 66826,
 1508622,
 1508624,
 197911,
 1508641,
 1344803,
 1508643,
 197942,
 230728,
 99677,
 230750,
 230761,
 460140,
 1312113,
 492916,
 165241,
 460158,
 1508741,
 230792,
 460173,
 198031,
 460177,
 1181078,
 99736,
 460186,
 1344922,
 230816,
 1082795,
 460205,
 1344945,
 1344959,
 394691,
 99781,
 1607111,
 525768,
 1508811,
 67020,
 1508819,
 1344980,
 1639893,
 99803,
 99804,
 1312228,
 394727,
 1541621,
 1312248,
 1639928,
 1541626,
 329212,
 67076,
 1181199,
 460307,
 1181203,
 1181205,
 493080,
 1181221,
 1508908,
 1508910,
 99888,
 263742,
 1508932,
 1640005,
 1508936,
 1181261,
 1508942,
 1541710,
 1640020,
 460373,
 1410657,
 263789,
 99993,
 394913,
 394920,
 362169,
 362170,
 67262,
 1312449,
 427716,
 1279714,
 1148652,
 362228,
 1640180,
 67320,
 165630,
 1148671,
 1083136,
 1607427,
 1345284,
 165637,
 1378053,
 1541896,
 34575,
 1640208,
 460572,
 67357,
 1640230,
 460584,
 1640234,
 526125,
 362297,
 1312573,
 1312608,
 1640288,
 1607528,
 427890,
 493426,
 1607538,
 67447,
 1312631,
 1574780,
 1607561,
 1607567,
 133018,
 1640377,
 526268,
 460734,
 1640385,
 1607622,
 1050576,
 460763,
 460774,
 362472,
 1542121,
 755698,
 1345525,
 198656,
 165908,
 493589,
 460840,
 493609,
 493633,
 493645,
 1345627,
 1149023,
 165987,
 362603,
 493677,
 1083504,
 460916,
 231542,
 493688,
 362618,
 493698,
 100483,
 1312900,
 493701,
 1214598,
 166035,
 362646,
 166041,
 198809,
 100509,
 166047,
 166051,
 362660,
 1607844,
 395430,
 1607847,
 231604,
 1607893,
 1607895,
 461039,
 461052,
 166148,
 1345802,
 1149196,
 330001,
 1083665,
 362780,
 362790,
 1345846,
 395587,
 67908,
 362820,
 198981,
 1313095,
 362825,
 1247587,
 1313129,
 493931,
 1345902,
 1640815,
 1313148,
 395645,
 1640829,
 1083776,
 493963,
 493967,
 1313169,
 1313170,
 362900,
 1345943,
 428458,
 1575341,
 428463,
 494001,
 1673657,
 1575357,
 166337,
 1313217,
 461251,
 166341,
 1346006,
 1149427,
 1378808,
 428544,
 461314,
 1673749,
 1215000,
 1608234,
 428593,
 1313331,
 428607,
 428614,
 1247836,
 1313378,
 1575536,
 494197,
 1051253,
 297593,
 428666,
 1641103,
 1149595,
 1608354,
 35494,
 101032,
 1182378,
 1313452,
 1149619,
 461510,
 68306,
 428756,
 1247961,
 1608411,
 199388,
 68317,
 1608444,
 1575684,
 1313541,
 1608454,
 1280779,
 1608470,
 1608476,
 264999,
 723753,
 396077,
 1280817,
 1542969,
 428862,
 101215,
 1280878,
 101237,
 1313657,
 527230,
 1608576,
 101276,
 101282,
 527290,
 1608638,
 330706,
 1051603,
 1608662,
 101350,
 1313777,
 1313782,
 1510408,
 101385,
 1182730,
 1313814,
 199718,
 527411,
 1575992,
 101434,
 1575999,
 1313856,
 101443,
 265285,
 1510480,
 1150037,
 101469,
 363618,
 1641583,
 527504,
 35989,
 101535,
 101561,
 1674444,
 527634,
 1084693,
 1346843,
 1314076,
 1412382,
 101681,
 200001,
 363843,
 527688,
 101706,
 101711,
 1609046,
 101719,
 527717,
 1609062,
 1150324,
 396664,
 396669,
 101775,
 527768,
 1576348,
 232864,
 1281481,
 364007,
 1609195,
 527856,
 1347057,
 1314292,
 364037,
 396814,
 1084953,
 101917,
 462371,
 1314341,
 1347123,
 1510981,
 1084999,
 1510984,
 1511008,
 101986,
 167522,
 527976,
 101996,
 1052270,
 1085054,
 1576576,
 528005,
 1085064,
 1642121,
 659082,
 429707,
 1314447,
 528022,
 429728,
 528034,
 102051,
 1085090,
 528039,
 1609403,
 626368,
 167619,
 1609412,
 167620,
 1347274,
 69326,
 528094,
 102134,
 200446,
 233217,
 1150728,
 397066,
 1543953,
 1609489,
 167701,
 397087,
 1576737,
 69410,
 1085221,
 1609516,
 69421,
 495405,
 1347382,
 167745,
 528195,
 528198,
 364364,
 167763,
 364390,
 528233,
 1052522,
 495480,
 1609592,
 397180,
 1052543,
 429955,
 429962,
 233364,
 233374,
 167840,
 1052577,
 495525,
 495528,
 1576873,
 364459,
 1052587,
 69552,
 69553,
 430005,
 1052598,
 364489,
 1347535,
 659408,
 69587,
 331734,
 1183708,
 1052645,
 364518,
 430059,
 1085419,
 1052654,
 1576942,
 233457,
 1085436,
 102406,
 102407,
 462859,
 1085451,
 1609741,
 1609744,
 233489,
 1052699,
 1609755,
 1052705,
 528420,
 1314864,
 233528,
 102459,
 1642555,
 397389,
 495698,
 266323,
 1052767,
 102506,
 69741,
 36983,
 102519,
 135299,
 233617,
 233624,
 1216665,
 528542,
 528549,
 135336,
 1052842,
 102575,
 1052847,
 102597,
 1052869,
 233676,
 102606,
 37079,
 1052898,
 1609958,
 69865,
 69866,
 200937,
 1085675,
 1216748,
 528627,
 69877,
 102645,
 69879,
 168183,
 1675511,
 1085690,
 69889,
 69893,
 69894,
 69895,
 528646,
 1052934,
 1052938,
 1315080,
 397581,
 1085723,
 69918,
 364838,
 1052968,
 1610025,
 1052970,
 102728,
 69965,
 233805,
 364884,
 528725,
 1216856,
 528730,
 528733,
 1675631,
 102770,
 1610104,
 1053053,
 1315197,
 1610112,
 70025,
 364940,
 102798,
 70031,
 266639,
 528790,
 1216928,
 70053,
 102834,
 233908,
 1544638,
 102847,
 233937,
 1053139,
 1053143,
 1085918,
 1053152,
 1151458,
 1053157,
 102886,
 1053162,
 1642990,
 102914,
 102915,
 233988,
 102917,
 233989,
 1610242,
 1610266,
 102956,
 135739,
 102973,
 758335,
 102983,
 1086044,
 528991,
 1053281,
 1053295,
 1086064,
 1151603,
 1643142,
 1282699,
 627340,
 529044,
 1053337,
 1544862,
 1086111,
 37540,
 1282725,
 1053350,
 1086121,
 1577648,
 1053361,
 1512114,
 1315505,
 1053365,
 1577662,
 1610432,
 529094,
 1184455,
 398040,
 1315547,
 1315561,
 1643250,
 463625,
 1315600,
 1643286,
 1577755,
 1151786,
 430896,
 1610547,
 234315,
 234322,
 430930,
 1315672,
 1053535,
 37731,
 1053545,
 1053547,
 496495,
 1053554,
 1315730,
 365465,
 529305,
 1086362,
 529314,
 431013,
 234409,
 1643435,
 1086385,
 1053621,
 1348535,
 201661,
 529345,
 529354,
 1512400,
 725969,
 1610706,
 234452,
 1315799,
 103389,
 398302,
 1577951,
 1053667,
 234472,
 496623,
 1577970,
 496655,
 70674,
 70685,
 1578015,
 1283108,
 1348648,
 1610797,
 1610818,
 1053765,
 234568,
 365640,
 1053770,
 365646,
 1610835,
 1086549,
 1086561,
 693347,
 1315956,
 1610871,
 1086590,
 398468,
 1086596,
 431246,
 103572,
 1086617,
 1610911,
 234667,
 398509,
 1053870,
 1053874,
 332978,
 1348793,
 136378,
 1086662,
 1316040,
 1348814,
 1086682,
 1086688,
 496867,
 234729,
 1086702,
 1578233,
 103682,
 1545481,
 103702,
 1053984,
 1053989,
 136487,
 1348915,
 1611060,
 1152316,
 1348926,
 70990,
 1054039,
 431450,
 1611107,
 1054053,
 431462,
 1643879,
 71024,
 1054069,
 1643897,
 202107,
 431487,
 431488,
 71049,
 234894,
 431502,
 1054095,
 431516,
 365988,
 431534,
 1152441,
 1316283,
 1512891,
 1152447,
 366028,
 136660,
 431572,
 1611226,
 1054176,
 71145,
 1250798,
 1316335,
 1644014,
 1644023,
 529921,
 38413,
 1578512,
 431637,
 366115,
 1087015,
 71211,
 1611312,
 1087026,
 38462,
 1644097,
 464450,
 267865,
 1054316,
 38538,
 1513106,
 1611421,
 1513120,
 1087137,
 1087183,
 235218,
 1513189,
 1611495,
 1349352,
 235249,
 235254,
 1644285,
 366334,
 464649,
 1087252,
 1382174,
 1316652,
 268078,
 1546036,
 137024,
 235329,
 1120068,
 431951,
 1578837,
 235351,
 1611609,
 1087335,
 1415023,
 1316726,
 1546110,
 1644416,
 1513346,
 1611657,
 104335,
 1578905,
 169882,
 1349534,
 1546143,
 1546153,
 235444,
 104379,
 104381,
 1447870,
 1578947,
 ...}

In [27]:
pd.set_option('max_row',200) 
pd.set_option('display.max_colwidth', 100)
pd.read_csv("/data/jupyter_root/dcube_data/no_name/feature_list.csv",sep=',')

,Unnamed: 0,Feature_combination,Standard,Poly
0,feature1,['time_stamp_day'],user_agent,nunique
1,feature2,['time_stamp_hour'],user_agent,nunique
2,feature3,['time_stamp_3hour'],user_agent,nunique
3,feature4,['time_stamp_6hour'],user_agent,nunique
4,feature5,['time_stamp_day'],os_version,nunique
5,feature6,['time_stamp_hour'],os_version,nunique
6,feature7,['time_stamp_3hour'],os_version,nunique
7,feature8,['time_stamp_6hour'],os_version,nunique
8,feature9,['time_stamp_day'],ip_1,nunique
9,feature10,['time_stamp_hour'],ip_1,nunique
10,feature11,['time_stamp_3hour'],ip_1,nunique
11,feature12,['time_stamp_6hour'],ip_1,nunique
12,feature13,['time_stamp_day'],ip_12,nunique
13,feature14,['time_stamp_hour'],ip_12,nunique
14,feature15,['time_stamp_3hour'],ip_12,nunique
15,feature16,['time_stamp_6hour'],ip_12,nunique
16,feature17,['time_stamp_day'],ip_123,nunique
17,feature18,['time_stamp_hour'],ip_123,nunique
18,feature19,['time_stamp_3hour'],ip_123,nunique
19,feature20,['time_stamp_6hour'],ip_123,nunique
20,feature21,['time_stamp_day'],ip_1234,nunique
21,feature22,['time_stamp_hour'],ip_1234,nunique
22,feature23,['time_stamp_3hour'],ip_1234,nunique
23,feature24,['time_stamp_6hour'],ip_1234,nunique
24,feature25,['time_stamp_day'],ip_city,nunique
25,feature26,['time_stamp_hour'],ip_city,nunique
26,feature27,['time_stamp_3hour'],ip_city,nunique
27,feature28,['time_stamp_6hour'],ip_city,nunique
28,feature29,['time_stamp_day'],resource_owner,nunique
29,feature30,['time_stamp_hour'],resource_owner,nunique
30,feature31,['time_stamp_3hour'],resource_owner,nunique
31,feature32,['time_stamp_6hour'],resource_owner,nunique
32,feature33,['time_stamp_day'],resource_type,nunique
33,feature34,['time_stamp_hour'],resource_type,nunique
34,feature35,['time_stamp_3hour'],resource_type,nunique
35,feature36,['time_stamp_6hour'],resource_type,nunique
36,feature37,['time_stamp_day'],resource_category,nunique
37,feature38,['time_stamp_hour'],resource_category,nunique
38,feature39,['time_stamp_3hour'],resource_category,nunique
39,feature40,['time_stamp_6hour'],resource_category,nunique
40,feature41,['event_type'],index,count
41,feature42,['time_stamp_day'],index,count
42,feature43,['time_stamp_hour'],index,count
43,feature44,['time_stamp_3hour'],index,count
44,feature45,['time_stamp_6hour'],index,count
45,feature46,"['user_agent', 'time_stamp_day']",index,count
46,feature47,"['user_agent', 'time_stamp_hour']",index,count
47,feature48,"['user_agent', 'time_stamp_3hour']",index,count
48,feature49,"['user_agent', 'time_stamp_6hour']",index,count
49,feature50,"['os_version', 'time_stamp_day']",index,count
50,feature51,"['os_version', 'time_stamp_hour']",index,count
51,feature52,"['os_version', 'time_stamp_3hour']",index,count
52,feature53,"['os_version', 'time_stamp_6hour']",index,count
53,feature54,"['ip_1', 'time_stamp_day']",index,count
54,feature55,"['ip_1', 'time_stamp_hour']",index,count
55,feature56,"['ip_1', 'time_stamp_3hour']",index,count
56,feature57,"['ip_1', 'time_stamp_6hour']",index,count
57,feature58,"['ip_12', 'time_stamp_day']",index,count
58,feature59,"['ip_12', 'time_stamp_hour']",index,count
59,feature60,"['ip_12', 'time_stamp_3hour']",index,count
60,feature61,"['ip_12', 'time_stamp_6hour']",index,count
61,feature62,"['ip_123', 'time_stamp_day']",index,count
62,feature63,"['ip_123', 'time_stamp_hour']",index,count
63,feature64,"['ip_123', 'time_stamp_3hour']",index,count
64,feature65,"['ip_123', 'time_stamp_6hour']",index,count
65,feature66,"['ip_1234', 'time_stamp_day']",index,count
66,feature67,"['ip_1234', 'time_stamp_hour']",index,count
67,feature68,"['ip_1234', 'time_stamp_3hour']",index,count
68,feature69,"['ip_1234', 'time_stamp_6hour']",index,count
69,feature70,"['ip_city', 'time_stamp_day']",index,count
70,feature71,"['ip_city', 'time_stamp_hour']",index,count
71,feature72,"['ip_city', 'time_stamp_3hour']",index,count
72,feature73,"['ip_city', 'time_stamp_6hour']",index,count
73,feature74,"['resource_owner', 'time_stamp_day']",index,count
74,feature75,"['resource_owner', 'time_stamp_hour']",index,count
75,feature76,"['resource_owner', 'time_stamp_3hour']",index,count
76,feature77,"['resource_owner', 'time_stamp_6hour']",index,count
77,feature78,"['resource_type', 'time_stamp_day']",index,count
78,feature79,"['resource_type', 'time_stamp_hour']",index,count
79,feature80,"['resource_type', 'time_stamp_3hour']",index,count
80,feature81,"['resource_type', 'time_stamp_6hour']",index,count
81,feature82,"['resource_category', 'time_stamp_day']",index,count
82,feature83,"['resource_category', 'time_stamp_hour']",index,count
83,feature84,"['resource_category', 'time_stamp_3hour']",index,count
84,feature85,"['resource_category', 'time_stamp_6hour']",index,count
85,feature86,"['user_agent', 'time_stamp_day', 'event_type']",index,count
86,feature87,"['user_agent', 'time_stamp_hour', 'event_type']",index,count
87,feature88,"['user_agent', 'time_stamp_3hour', 'event_type']",index,count
88,feature89,"['user_agent', 'time_stamp_6hour', 'event_type']",index,count
89,feature90,"['os_version', 'time_stamp_day', 'event_type']",index,count
90,feature91,"['os_version', 'time_stamp_hour', 'event_type']",index,count
91,feature92,"['os_version', 'time_stamp_3hour', 'event_type']",index,count
92,feature93,"['os_version', 'time_stamp_6hour', 'event_type']",index,count
93,feature94,"['ip_1', 'time_stamp_day', 'event_type']",index,count
94,feature95,"['ip_1', 'time_stamp_hour', 'event_type']",index,count
95,feature96,"['ip_1', 'time_stamp_3hour', 'event_type']",index,count
96,feature97,"['ip_1', 'time_stamp_6hour', 'event_type']",index,count
97,feature98,"['ip_12', 'time_stamp_day', 'event_type']",index,count
98,feature99,"['ip_12', 'time_stamp_hour', 'event_type']",index,count
99,feature100,"['ip_12', 'time_stamp_3hour', 'event_type']",index,count
100,feature101,"['ip_12', 'time_stamp_6hour', 'event_type']",index,count
101,feature102,"['ip_123', 'time_stamp_day', 'event_type']",index,count
102,feature103,"['ip_123', 'time_stamp_hour', 'event_type']",index,count
103,feature104,"['ip_123', 'time_stamp_3hour', 'event_type']",index,count
104,feature105,"['ip_123', 'time_stamp_6hour', 'event_type']",index,count
105,feature106,"['ip_1234', 'time_stamp_day', 'event_type']",index,count
106,feature107,"['ip_1234', 'time_stamp_hour', 'event_type']",index,count
107,feature108,"['ip_1234', 'time_stamp_3hour', 'event_type']",index,count
108,feature109,"['ip_1234', 'time_stamp_6hour', 'event_type']",index,count
109,feature110,"['ip_city', 'time_stamp_day', 'event_type']",index,count
110,feature111,"['ip_city', 'time_stamp_hour', 'event_type']",index,count
111,feature112,"['ip_city', 'time_stamp_3hour', 'event_type']",index,count
112,feature113,"['ip_city', 'time_stamp_6hour', 'event_type']",index,count
113,feature114,"['resource_owner', 'time_stamp_day', 'event_type']",index,count
114,feature115,"['resource_owner', 'time_stamp_hour', 'event_type']",index,count
115,feature116,"['resource_owner', 'time_stamp_3hour', 'event_type']",index,count
116,feature117,"['resource_owner', 'time_stamp_6hour', 'event_type']",index,count
117,feature118,"['resource_type', 'time_stamp_day', 'event_type']",index,count
118,feature119,"['resource_type', 'time_stamp_hour', 'event_type']",index,count
119,feature120,"['resource_type', 'time_stamp_3hour', 'event_type']",index,count
120,feature121,"['resource_type', 'time_stamp_6hour', 'event_type']",index,count
121,feature122,"['resource_category', 'time_stamp_day', 'event_type']",index,count
122,feature123,"['resource_category', 'time_stamp_hour', 'event_type']",index,count
123,feature124,"['resource_category', 'time_stamp_3hour', 'event_type']",index,count
124,feature125,"['resource_category', 'time_stamp_6hour', 'event_type']",index,count

In [12]:
pd.set_option('max_row',200) 
pd.set_option('display.max_colwidth', 100)
pd.read_csv("/data/jupyter_root/dcube_data/no_name_add/feature_list.csv",sep=',')

,Unnamed: 0,Feature_combination,Standard,Poly
0,feature126,['user_agent'],user_name,nunique
1,feature127,"['user_agent', 'time_stamp_day']",user_name,nunique
2,feature128,"['user_agent', 'time_stamp_hour']",user_name,nunique
3,feature129,"['user_agent', 'time_stamp_3hour']",user_name,nunique
4,feature130,"['user_agent', 'time_stamp_6hour']",user_name,nunique
5,feature131,['os_version'],user_name,nunique
6,feature132,"['os_version', 'time_stamp_day']",user_name,nunique
7,feature133,"['os_version', 'time_stamp_hour']",user_name,nunique
8,feature134,"['os_version', 'time_stamp_3hour']",user_name,nunique
9,feature135,"['os_version', 'time_stamp_6hour']",user_name,nunique
10,feature136,['resource_owner'],user_name,nunique
11,feature137,"['resource_owner', 'time_stamp_day']",user_name,nunique
12,feature138,"['resource_owner', 'time_stamp_hour']",user_name,nunique
13,feature139,"['resource_owner', 'time_stamp_3hour']",user_name,nunique
14,feature140,"['resource_owner', 'time_stamp_6hour']",user_name,nunique
15,feature141,['resource_type'],user_name,nunique
16,feature142,"['resource_type', 'time_stamp_day']",user_name,nunique
17,feature143,"['resource_type', 'time_stamp_hour']",user_name,nunique
18,feature144,"['resource_type', 'time_stamp_3hour']",user_name,nunique
19,feature145,"['resource_type', 'time_stamp_6hour']",user_name,nunique
20,feature146,['resource_category'],user_name,nunique
21,feature147,"['resource_category', 'time_stamp_day']",user_name,nunique
22,feature148,"['resource_category', 'time_stamp_hour']",user_name,nunique
23,feature149,"['resource_category', 'time_stamp_3hour']",user_name,nunique
24,feature150,"['resource_category', 'time_stamp_6hour']",user_name,nunique
25,feature151,['ip_1'],user_name,nunique
26,feature152,"['ip_1', 'time_stamp_day']",user_name,nunique
27,feature153,"['ip_1', 'time_stamp_hour']",user_name,nunique
28,feature154,"['ip_1', 'time_stamp_3hour']",user_name,nunique
29,feature155,"['ip_1', 'time_stamp_6hour']",user_name,nunique
30,feature156,['ip_12'],user_name,nunique
31,feature157,"['ip_12', 'time_stamp_day']",user_name,nunique
32,feature158,"['ip_12', 'time_stamp_hour']",user_name,nunique
33,feature159,"['ip_12', 'time_stamp_3hour']",user_name,nunique
34,feature160,"['ip_12', 'time_stamp_6hour']",user_name,nunique
35,feature161,['ip_123'],user_name,nunique
36,feature162,"['ip_123', 'time_stamp_day']",user_name,nunique
37,feature163,"['ip_123', 'time_stamp_hour']",user_name,nunique
38,feature164,"['ip_123', 'time_stamp_3hour']",user_name,nunique
39,feature165,"['ip_123', 'time_stamp_6hour']",user_name,nunique
40,feature166,['ip_1234'],user_name,nunique
41,feature167,"['ip_1234', 'time_stamp_day']",user_name,nunique
42,feature168,"['ip_1234', 'time_stamp_hour']",user_name,nunique
43,feature169,"['ip_1234', 'time_stamp_3hour']",user_name,nunique
44,feature170,"['ip_1234', 'time_stamp_6hour']",user_name,nunique
45,feature171,['ip_city'],user_name,nunique
46,feature172,"['ip_city', 'time_stamp_day']",user_name,nunique
47,feature173,"['ip_city', 'time_stamp_hour']",user_name,nunique
48,feature174,"['ip_city', 'time_stamp_3hour']",user_name,nunique
49,feature175,"['ip_city', 'time_stamp_6hour']",user_name,nunique
50,feature176,"['os_version', 'user_agent']",user_name,nunique
51,feature177,"['resource_owner', 'user_agent']",user_name,nunique
52,feature178,"['resource_type', 'user_agent']",user_name,nunique
53,feature179,"['resource_category', 'user_agent']",user_name,nunique
54,feature180,"['ip_1', 'user_agent']",user_name,nunique
55,feature181,"['ip_12', 'user_agent']",user_name,nunique
56,feature182,"['ip_123', 'user_agent']",user_name,nunique
57,feature183,"['ip_1234', 'user_agent']",user_name,nunique
58,feature184,"['ip_city', 'user_agent']",user_name,nunique
59,feature185,"['resource_owner', 'os_version']",user_name,nunique
60,feature186,"['resource_type', 'os_version']",user_name,nunique
61,feature187,"['resource_category', 'os_version']",user_name,nunique
62,feature188,"['ip_1', 'os_version']",user_name,nunique
63,feature189,"['ip_12', 'os_version']",user_name,nunique
64,feature190,"['ip_123', 'os_version']",user_name,nunique
65,feature191,"['ip_1234', 'os_version']",user_name,nunique
66,feature192,"['ip_city', 'os_version']",user_name,nunique
67,feature193,"['resource_type', 'resource_owner']",user_name,nunique
68,feature194,"['resource_category', 'resource_owner']",user_name,nunique
69,feature195,"['ip_1', 'resource_owner']",user_name,nunique
70,feature196,"['ip_12', 'resource_owner']",user_name,nunique
71,feature197,"['ip_123', 'resource_owner']",user_name,nunique
72,feature198,"['ip_1234', 'resource_owner']",user_name,nunique
73,feature199,"['ip_city', 'resource_owner']",user_name,nunique
74,feature200,"['resource_category', 'resource_type']",user_name,nunique
75,feature201,"['ip_1', 'resource_type']",user_name,nunique
76,feature202,"['ip_12', 'resource_type']",user_name,nunique
77,feature203,"['ip_123', 'resource_type']",user_name,nunique
78,feature204,"['ip_1234', 'resource_type']",user_name,nunique
79,feature205,"['ip_city', 'resource_type']",user_name,nunique
80,feature206,"['ip_1', 'resource_category']",user_name,nunique
81,feature207,"['ip_12', 'resource_category']",user_name,nunique
82,feature208,"['ip_123', 'resource_category']",user_name,nunique
83,feature209,"['ip_1234', 'resource_category']",user_name,nunique
84,feature210,"['ip_city', 'resource_category']",user_name,nunique
85,feature211,['user_agent'],user_name,count
86,feature212,"['user_agent', 'time_stamp_day']",user_name,count
87,feature213,"['user_agent', 'time_stamp_hour']",user_name,count
88,feature214,"['user_agent', 'time_stamp_3hour']",user_name,count
89,feature215,"['user_agent', 'time_stamp_6hour']",user_name,count
90,feature216,['os_version'],user_name,count
91,feature217,"['os_version', 'time_stamp_day']",user_name,count
92,feature218,"['os_version', 'time_stamp_hour']",user_name,count
93,feature219,"['os_version', 'time_stamp_3hour']",user_name,count
94,feature220,"['os_version', 'time_stamp_6hour']",user_name,count
95,feature221,['resource_owner'],user_name,count
96,feature222,"['resource_owner', 'time_stamp_day']",user_name,count
97,feature223,"['resource_owner', 'time_stamp_hour']",user_name,count
98,feature224,"['resource_owner', 'time_stamp_3hour']",user_name,count
99,feature225,"['resource_owner', 'time_stamp_6hour']",user_name,count
...,...,...,...,...
115,feature241,['ip_12'],user_name,count
116,feature242,"['ip_12', 'time_stamp_day']",user_name,count
117,feature243,"['ip_12', 'time_stamp_hour']",user_name,count
118,feature244,"['ip_12', 'time_stamp_3hour']",user_name,count
119,feature245,"['ip_12', 'time_stamp_6hour']",user_name,count
120,feature246,['ip_123'],user_name,count
121,feature247,"['ip_123', 'time_stamp_day']",user_name,count
122,feature248,"['ip_123', 'time_stamp_hour']",user_name,count
123,feature249,"['ip_123', 'time_stamp_3hour']",user_name,count
124,feature250,"['ip_123', 'time_stamp_6hour']",user_name,count
125,feature251,['ip_1234'],user_name,count
126,feature252,"['ip_1234', 'time_stamp_day']",user_name,count
127,feature253,"['ip_1234', 'time_stamp_hour']",user_name,count
128,feature254,"['ip_1234', 'time_stamp_3hour']",user_name,count
129,feature255,"['ip_1234', 'time_stamp_6hour']",user_name,count
130,feature256,['ip_city'],user_name,count
131,feature257,"['ip_city', 'time_stamp_day']",user_name,count
132,feature258,"['ip_city', 'time_stamp_hour']",user_name,count
133,feature259,"['ip_city', 'time_stamp_3hour']",user_name,count
134,feature260,"['ip_city', 'time_stamp_6hour']",user_name,count
135,feature261,"['os_version', 'user_agent']",user_name,count
136,feature262,"['resource_owner', 'user_agent']",user_name,count
137,feature263,"['resource_type', 'user_agent']",user_name,count
138,feature264,"['resource_category', 'user_agent']",user_name,count
139,feature265,"['ip_1', 'user_agent']",user_name,count
140,feature266,"['ip_12', 'user_agent']",user_name,count
141,feature267,"['ip_123', 'user_agent']",user_name,count
142,feature268,"['ip_1234', 'user_agent']",user_name,count
143,feature269,"['ip_city', 'user_agent']",user_name,count
144,feature270,"['resource_owner', 'os_version']",user_name,count
145,feature271,"['resource_type', 'os_version']",user_name,count
146,feature272,"['resource_category', 'os_version']",user_name,count
147,feature273,"['ip_1', 'os_version']",user_name,count
148,feature274,"['ip_12', 'os_version']",user_name,count
149,feature275,"['ip_123', 'os_version']",user_name,count
150,feature276,"['ip_1234', 'os_version']",user_name,count
151,feature277,"['ip_city', 'os_version']",user_name,count
152,feature278,"['resource_type', 'resource_owner']",user_name,count
153,feature279,"['resource_category', 'resource_owner']",user_name,count
154,feature280,"['ip_1', 'resource_owner']",user_name,count
155,feature281,"['ip_12', 'resource_owner']",user_name,count
156,feature282,"['ip_123', 'resource_owner']",user_name,count
157,feature283,"['ip_1234', 'resource_owner']",user_name,count
158,feature284,"['ip_city', 'resource_owner']",user_name,count
159,feature285,"['resource_category', 'resource_type']",user_name,count
160,feature286,"['ip_1', 'resource_type']",user_name,count
161,feature287,"['ip_12', 'resource_type']",user_name,count
162,feature288,"['ip_123', 'resource_type']",user_name,count
163,feature289,"['ip_1234', 'resource_type']",user_name,count
164,feature290,"['ip_city', 'resource_type']",user_name,count
165,feature291,"['ip_1', 'resource_category']",user_name,count
166,feature292,"['ip_12', 'resource_category']",user_name,count
167,feature293,"['ip_123', 'resource_category']",user_name,count
168,feature294,"['ip_1234', 'resource_category']",user_name,count
169,feature295,"['ip_city', 'resource_category']",user_name,count
170,feature296,['event_type'],user_name,nunique
171,feature297,['time_stamp_day'],user_name,nunique
172,feature298,['time_stamp_hour'],user_name,nunique
173,feature299,['time_stamp_3hour'],user_name,nunique
174,feature300,['time_stamp_6hour'],user_name,nunique
175,feature301,"['user_agent', 'time_stamp_day', 'event_type']",user_name,nunique
176,feature302,"['user_agent', 'time_stamp_hour', 'event_type']",user_name,nunique
177,feature303,"['user_agent', 'time_stamp_3hour', 'event_type']",user_name,nunique
178,feature304,"['user_agent', 'time_stamp_6hour', 'event_type']",user_name,nunique
179,feature305,"['os_version', 'time_stamp_day', 'event_type']",user_name,nunique
180,feature306,"['os_version', 'time_stamp_hour', 'event_type']",user_name,nunique
181,feature307,"['os_version', 'time_stamp_3hour', 'event_type']",user_name,nunique
182,feature308,"['os_version', 'time_stamp_6hour', 'event_type']",user_name,nunique
183,feature309,"['resource_owner', 'time_stamp_day', 'event_type']",user_name,nunique
184,feature310,"['resource_owner', 'time_stamp_hour', 'event_type']",user_name,nunique
185,feature311,"['resource_owner', 'time_stamp_3hour', 'event_type']",user_name,nunique
186,feature312,"['resource_owner', 'time_stamp_6hour', 'event_type']",user_name,nunique
187,feature313,"['resource_type', 'time_stamp_day', 'event_type']",user_name,nunique
188,feature314,"['resource_type', 'time_stamp_hour', 'event_type']",user_name,nunique
189,feature315,"['resource_type', 'time_stamp_3hour', 'event_type']",user_name,nunique
190,feature316,"['resource_type', 'time_stamp_6hour', 'event_type']",user_name,nunique
191,feature317,"['resource_category', 'time_stamp_day', 'event_type']",user_name,nunique
192,feature318,"['resource_category', 'time_stamp_hour', 'event_type']",user_name,nunique
193,feature319,"['resource_category', 'time_stamp_3hour', 'event_type']",user_name,nunique
194,feature320,"['resource_category', 'time_stamp_6hour', 'event_type']",user_name,nunique
195,feature321,"['ip_1', 'time_stamp_day', 'event_type']",user_name,nunique
196,feature322,"['ip_1', 'time_stamp_hour', 'event_type']",user_name,nunique
197,feature323,"['ip_1', 'time_stamp_3hour', 'event_type']",user_name,nunique
198,feature324,"['ip_1', 'time_stamp_6hour', 'event_type']",user_name,nunique
199,feature325,"['ip_12', 'time_stamp_day', 'event_type']",user_name,nunique
200,feature326,"['ip_12', 'time_stamp_hour', 'event_type']",user_name,nunique
201,feature327,"['ip_12', 'time_stamp_3hour', 'event_type']",user_name,nunique
202,feature328,"['ip_12', 'time_stamp_6hour', 'event_type']",user_name,nunique
203,feature329,"['ip_123', 'time_stamp_day', 'event_type']",user_name,nunique
204,feature330,"['ip_123', 'time_stamp_hour', 'event_type']",user_name,nunique
205,feature331,"['ip_123', 'time_stamp_3hour', 'event_type']",user_name,nunique
206,feature332,"['ip_123', 'time_stamp_6hour', 'event_type']",user_name,nunique
207,feature333,"['ip_1234', 'time_stamp_day', 'event_type']",user_name,nunique
208,feature334,"['ip_1234', 'time_stamp_hour', 'event_type']",user_name,nunique
209,feature335,"['ip_1234', 'time_stamp_3hour', 'event_type']",user_name,nunique
210,feature336,"['ip_1234', 'time_stamp_6hour', 'event_type']",user_name,nunique
211,feature337,"['ip_city', 'time_stamp_day', 'event_type']",user_name,nunique
212,feature338,"['ip_city', 'time_stamp_hour', 'event_type']",user_name,nunique
213,feature339,"['ip_city', 'time_stamp_3hour', 'event_type']",user_name,nunique
214,feature340,"['ip_city', 'time_stamp_6hour', 'event_type']",user_name,nunique

In [7]:
pd.set_option('max_row',200) 
pd.set_option('display.max_colwidth', 100)
pd.read_csv("/data/jupyter_root/dcube_data/no_name_add/result_list2_811.csv",sep=',')

,feature_user,block_1.tuples,block_2.tuples,block_3.tuples,block_4.tuples,block_5.tuples
0,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167..."
1,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 245766, 1597450, 319501, 1310734, 221217, 65569, 548900, 1130535, 41012, 1589314, 2212...","{1130498, 466948, 286725, 245766, 319501, 81934, 1310734, 1327123, 516120, 221211, 65569, 548900...","{1130498, 1089538, 466949, 499719, 1310734, 1646615, 65569, 1130535, 1089592, 114747, 1638472, 1...","{466948, 1658884, 546826, 1601547, 1310734, 1548306, 1529874, 118805, 1343510, 544789, 221211, 1...","{1595392, 1089538, 1658884, 245766, 499719, 221192, 348169, 546826, 141325, 1433614, 1556496, 12..."
2,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{20487, 221192, 1514503, 1182730, 76304, 1165329, 1548306, 282649, 521755, 1590812, 160289, 2207...","{280576, 373249, 389632, 102914, 395264, 160268, 319501, 1652756, 520214, 73243, 65569, 1583652,...","{198656, 73218, 117763, 114182, 1604102, 92681, 1573897, 1464845, 1290254, 453138, 1653782, 5207...","{1508352, 461314, 1343494, 245766, 118796, 1464845, 1313814, 471065, 73243, 250396, 118817, 6556...","{1576450, 1090563, 419333, 116742, 519687, 1524743, 118805, 116761, 542748, 475676, 366110, 2150..."
3,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{280576, 395264, 317450, 319501, 81934, 1308689, 1327123, 1652756, 118805, 520214, 1656859, 6556...","{1343494, 1536007, 245766, 1597450, 118796, 319501, 118805, 471065, 1607712, 118817, 65569, 5489...","{245766, 20487, 221192, 1165329, 1548306, 282649, 116788, 1071162, 520253, 1656894, 1052743, 577...","{116742, 1323024, 118805, 1646615, 116761, 542748, 1587229, 215072, 1634346, 479275, 550958, 107...","{198656, 245766, 1290254, 1298455, 215072, 460840, 1177644, 116788, 471108, 71753, 397389, 13067..."
4,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{280576, 1650688, 395264, 286725, 317450, 319501, 81934, 1308689, 1327123, 1652756, 118805, 5202...","{1595392, 243714, 1644547, 466948, 102406, 499719, 546826, 419854, 1290254, 1556498, 1327123, 52...","{1343494, 1536007, 245766, 317450, 1597450, 118796, 319501, 118805, 471065, 503836, 1607712, 118...","{1089538, 116742, 1323024, 118805, 1646615, 1595415, 116761, 542748, 1587229, 1585183, 282656, 2...","{1601547, 118805, 1343510, 544789, 102430, 1251361, 548900, 528420, 542765, 247858, 178232, 1308..."
5,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 245766, 1323028, 247832, 1308713, 1316907, 1212475, 348223, 471108, 1321029, 1052743, ...","{1343494, 245766, 1085451, 1316875, 1433614, 669711, 1323024, 1331217, 1310734, 1323028, 1333269...","{745476, 1343494, 1308689, 1327123, 563221, 1343510, 471065, 284700, 41012, 178232, 471108, 5776...","{1338373, 163336, 1540628, 1336853, 1326614, 1502744, 280095, 1212475, 1347137, 523330, 547399, ..."
6,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1089538, 466948, 221192, 1548306, 1343510, 1671197, 1089592, 1097784, 1597498, 41040, 1630303, ...","{1343494, 245766, 1323028, 247832, 1308713, 1316907, 1212475, 348223, 471108, 1321029, 1052743, ...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{745476, 1343494, 1316875, 1323024, 1308689, 1327123, 1323028, 1343510, 1337369, 471065, 284700,..."
7,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1089538, 466948, 221192, 1310734, 1548306, 1343510, 1671197, 65569, 1097772, 1089592, 1597498, ...","{1343494, 245766, 1323028, 247832, 1308713, 1316907, 1212475, 348223, 471108, 1321029, 1052743, ...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 65582, 1146929, 1671217, 1671221, ..."
8,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 1085451, 1316875, 1433614, 669711, 1323024, 1331217, 1310734, 1323028, 1333269, 134351...","{745476, 1343494, 1433614, 1310734, 1323024, 1308689, 1327123, 1323028, 1343510, 1337369, 471065...","{1343494, 1085451, 1316875, 1433614, 669711, 1323024, 1331217, 1310734, 1323028, 563221, 1333269..."
9,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{745476, 1343494, 245766, 1085451, 1316875, 1310734, 669711, 1323024, 1308689, 1331217, 1327123,...","{745476, 1343494, 245766, 1085451, 1316875, 1433614, 669711, 1323024, 1308689, 1331217, 1310734,...","{1329920, 1158401, 1204865, 155009, 1587845, 215301, 655113, 433163, 682766, 1325968, 1140500, 6...","{1565955, 498563, 1338373, 1614091, 682766, 1540628, 1343510, 196378, 474020, 1351337, 1328553, ..."
10,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1337216, 1204865, 1329035, 1286284, 1433614, 648975, 1325968, 1264283, 1311644, 654619, 1412382...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 65569, 65582, 1212475, 524351, 393281, 656...","{172546, 116742, 444809, 383246, 676496, 156567, 533914, 118814, 283943, 1541160, 1594539, 22199..."
11,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1339910, 163336, 1433614, 1087015, 140328, 52275, 41012, 1319481, 1624648, 1344587, 1306705, 13...","{1329920, 1158401, 1204865, 155009, 1587845, 215301, 655113, 433163, 682766, 1325968, 1140500, 6...","{1556480, 1130498, 1089538, 286725, 1343494, 245766, 221192, 466949, 1556494, 1204240, 1294353, ..."
12,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1660930, 1089538, 116742, 221192, 233489, 1343510, 1671197, 118814, 108576, 157734, 204839, 460...","{1337216, 1204865, 1329035, 1286284, 1433614, 648975, 1325968, 1264283, 1311644, 654619, 1412382...","{1339910, 163336, 433163, 317972, 1343510, 1087015, 140328, 52275, 41012, 1344587, 1251930, 1340..."
13,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655..."
14,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 65598, 5243...","{1130498, 1089538, 466948, 286725, 499719, 221192, 1556488, 458762, 81934, 1433614, 1204240, 154...","{137218, 1089538, 116742, 221192, 458762, 546826, 1085451, 419854, 118800, 1593363, 1564693, 134...","{172546, 137735, 501255, 1180681, 419854, 405006, 1646094, 498705, 1548306, 1523217, 1307156, 10...","{428544, 172546, 116742, 92681, 1590812, 118814, 95774, 160289, 462371, 1629734, 1569832, 154116..."
15,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1660930, 1089538, 116742, 221192, 1658889, 546826, 419854, 1548306, 1343510, 1052699, 1671197, ...","{1524736, 428544, 172546, 343043, 1180162, 92681, 1085451, 277004, 1539595, 1646094, 171534, 348...","{1539844, 116742, 1286284, 222092, 383246, 1343252, 1358101, 156567, 770842, 533914, 1157662, 11...","{523105, 172546, 222274, 283943, 420744, 247400, 676496, 1171188, 613781, 533914, 94590}"
16,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1660930, 1089538, 116742, 221192, 233489, 165908, 1343510, 1052699, 546845, 118814, 1671197, 10...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655..."
17,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 65598, 52435...","{1089538, 466948, 466949, 1343494, 499719, 221192, 1556488, 1597450, 245766, 81934, 221199, 1548...","{1556480, 466948, 286725, 245766, 499719, 221192, 466949, 81934, 1556495, 1204240, 516120, 54890...","{1130498, 1644547, 245766, 81934, 1593363, 165908, 118805, 1323028, 1505303, 116774, 204839, 235...","{461314, 1644547, 1522181, 1510408, 92681, 1303050, 498184, 160268, 1590285, 191499, 1523217, 15..."
18,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 65598, 52435...","{1089538, 466948, 466949, 1343494, 499719, 221192, 1556488, 1597450, 245766, 81934, 221199, 1548...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 1343510, 1671197, 65569, 32805, 65582, 1146929, 1671224, 65598, 524351, 393281, 65602,...","{466948, 1343494, 499719, 221192, 245766, 1556495, 1343510, 532517, 1130535, 1097770, 41012, 108..."
19,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 65598, 52435...","{1343494, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 65598, 5243...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 524...","{1556480, 1130498, 1089538, 466948, 286725, 1343494, 499719, 221192, 1556488, 1597450, 245766, 4..."
20,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 65598, 39328...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1556480, 1644547, 466948, 286725, 245766, 221192, 1658889, 546826, 81934, 419854, 1204240, 1308...","{1343494, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 65598, 524351, 393281, 65602,...","{1556480, 1130498, 466948, 286725, 245766, 221192, 1556488, 1597450, 81934, 221199, 1204240, 155..."
21,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 1671224, 65598, 524351, 3932...","{1556480, 1130498, 1089538, 466948, 745476, 1343494, 499719, 221192, 1556488, 245766, 466949, 81...","{1660930, 745476, 286725, 499719, 1556488, 458762, 81934, 419854, 215055, 145423, 165908, 133326...","{1592193, 172546, 343043, 1568259, 1564545, 1130246, 1650444, 1594637, 471182, 405006, 1538318, ...","{308234, 1167883, 1590285, 292877, 334868, 1647648, 118305, 1649189, 425004, 398385, 1347123, 15..."
22,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 1671224, 65598, 524351, 3932...","{1343494, 1671194, 1671197, 65569, 65582, 1671224, 65598, 524351, 393281, 65602, 1638472, 154016...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 1146929, 1671224, 65598, 524351, 39...","{1556480, 1130498, 1089538, 466948, 286725, 745476, 1343494, 221192, 1556488, 1597450, 245766, 4...","{1089538, 466948, 1343494, 499719, 221192, 1556488, 458762, 81934, 1433614, 1556495, 1548306, 13..."
23,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 1671224, 65598, 524351, 393281, 1638...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 65582, 1671224, 65598, 524351, 3932...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 1146929, 1671224, 65598, 524...","{1556480, 1130498, 1089538, 466948, 745476, 1343494, 466949, 221192, 458762, 1597450, 81934, 155...","{1089538, 466948, 286725, 1343494, 245766, 221192, 458762, 1556495, 1204240, 1548306, 1564693, 1..."
24,"{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 1671224, 65598, 524351, 3932...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655...","{1556480, 1089538, 466948, 745476, 1343494, 499719, 221192, 1556488, 245766, 1433614, 1556495, 1...","{395264, 1595392, 466948, 745476, 1343494, 499719, 221192, 102406, 118796, 1556495, 1609744, 118...","{1343494, 458762, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 1671224, 655..."
25,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{198656, 317444, 1601547, 1052699, 65569, 1177644, 520253, 1564734, 1611845, 1302614, 118880, 11...","{320006, 116742, 1524742, 1182730, 277004, 1433614, 1523217, 1180181, 1540634, 1180187, 1637919,...","{198656, 320006, 1645581, 1180695, 1502744, 1100314, 118305, 1283108, 1654309, 1608230, 501292, ...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167..."
26,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1089538, 245766, 499719, 221192, 81934, 1310734, 1548306, 1343510, 204822, 1671194, 221211, 167...","{198656, 1601547, 1433614, 1052699, 65569, 1177644, 520253, 1564734, 118880, 1650787, 1169517, 1...","{1089538, 286725, 245766, 499719, 221192, 466949, 1310734, 1204240, 1548306, 204822, 1671194, 65...","{137218, 626693, 1343494, 1323024, 448534, 1540121, 282653, 118814, 464929, 1052708, 1308712, 54..."
27,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1089538, 466948, 745476, 245766, 1556494, 1343510, 1671194, 1671197, 65569, 548900, 1589291, 10...","{1595904, 198656, 1520131, 317444, 601093, 1601547, 1180181, 1180695, 1502744, 1100314, 1180187,...","{1130498, 1089538, 466948, 245766, 221192, 1433614, 1310734, 1204240, 1556495, 1548306, 1556498,...","{1556480, 1089538, 466949, 1343494, 499719, 245766, 1597450, 319501, 81934, 1310734, 1327123, 16..."
28,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1089538, 466948, 1343494, 245766, 221192, 1597450, 319501, 1343510, 1671197, 65569, 548900, 204...","{198656, 317444, 116742, 1601547, 1052699, 65569, 1177644, 520253, 1564734, 1302614, 118880, 116...","{1089538, 466948, 245766, 1433614, 1556495, 204822, 221211, 548900, 532517, 1097770, 1097772, 14...","{1130498, 466949, 245766, 221192, 1556494, 1433614, 1204240, 1646615, 1597465, 1671197, 65569, 1..."
29,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671197, 65569, 1146929, 1671217, 1671221, 1671224,...","{1343494, 458762, 1310734, 1671194, 1671197, 65569, 32805, 65582, 1212475, 524351, 65602, 154017...","{1130498, 1089538, 466948, 466949, 245766, 499719, 1556488, 1556494, 1310734, 1556495, 1556498, ...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167..."
30,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671197, 65569, 1146929, 1671217, 1671221, 1671224,...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1212475, 655...","{1130498, 1089538, 286725, 245766, 466949, 319501, 1556494, 1556495, 1548306, 1646615, 221208, 1...","{1658884, 221192, 1085451, 1556494, 1529874, 118805, 221211, 1671197, 118814, 548900, 544809, 16...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167..."
31,"{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167...","{1343494, 458762, 1310734, 1343510, 1540121, 1671197, 65569, 1146929, 1671217, 1671221, 1671224,...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1671221, 167...","{1089538, 466949, 245766, 1556495, 1097770, 1490992, 1097784, 114747, 1056832, 442446, 65614, 65...","{1650688, 116742, 77833, 215055, 1323024, 1529874, 118805, 221211, 1671197, 118814, 1251361, 544...","{1343494, 458762, 1310734, 1343510, 1540121, 1671194, 1671197, 65569, 32805, 65582, 1146929, 167..."